/** GENERATED by scripts/build-spot-scenes.py from scripts/spot-themes.json and the images in
 * public/images/spot/ — do not hand-edit. Each zone is one or more [x0, x1, y0, y1] rectangles in
 * % of the panel (where an object's center may go); aspect is the sticker's width / height;
 * flippable says whether a mirror-flip is a visible difference for that picture. */
export interface SpotSprite {
  id: string
  zones: string[]
  aspect: number
  flippable: boolean
}

export interface SpotTheme {
  id: string
  zones: Record<string, [number, number, number, number][]>
  sprites: SpotSprite[]
}

export const SPOT_THEMES: SpotTheme[] = [
  {
    "id": "sea",
    "zones": {
      "sky": [
        [
          8,
          92,
          6,
          30
        ]
      ],
      "sea": [
        [
          10,
          90,
          52,
          57
        ],
        [
          26,
          74,
          68,
          82
        ]
      ],
      "sand": [
        [
          12,
          88,
          58,
          64
        ],
        [
          5,
          22,
          64,
          78
        ],
        [
          80,
          95,
          64,
          78
        ]
      ]
    },
    "sprites": [
      {
        "id": "crab",
        "zones": [
          "sand"
        ],
        "aspect": 1.101,
        "flippable": false
      },
      {
        "id": "fish",
        "zones": [
          "sea"
        ],
        "aspect": 1.304,
        "flippable": true
      },
      {
        "id": "sailboat",
        "zones": [
          "sea"
        ],
        "aspect": 0.796,
        "flippable": true
      },
      {
        "id": "starfish",
        "zones": [
          "sand",
          "sea"
        ],
        "aspect": 0.921,
        "flippable": false
      },
      {
        "id": "shell",
        "zones": [
          "sand"
        ],
        "aspect": 0.971,
        "flippable": false
      },
      {
        "id": "octopus",
        "zones": [
          "sea",
          "sand"
        ],
        "aspect": 0.996,
        "flippable": false
      },
      {
        "id": "beachball",
        "zones": [
          "sand"
        ],
        "aspect": 0.983,
        "flippable": false
      },
      {
        "id": "bucket",
        "zones": [
          "sand"
        ],
        "aspect": 0.946,
        "flippable": true
      },
      {
        "id": "seagull",
        "zones": [
          "sky"
        ],
        "aspect": 1.212,
        "flippable": true
      },
      {
        "id": "sandcastle",
        "zones": [
          "sand"
        ],
        "aspect": 1.086,
        "flippable": false
      },
      {
        "id": "whale",
        "zones": [
          "sea"
        ],
        "aspect": 1.6,
        "flippable": true
      },
      {
        "id": "turtle",
        "zones": [
          "sand",
          "sea"
        ],
        "aspect": 1.067,
        "flippable": true
      },
      {
        "id": "surfboard",
        "zones": [
          "sand"
        ],
        "aspect": 0.242,
        "flippable": false
      },
      {
        "id": "sunglasses",
        "zones": [
          "sand"
        ],
        "aspect": 2.376,
        "flippable": false
      },
      {
        "id": "windmill",
        "zones": [
          "sand"
        ],
        "aspect": 0.771,
        "flippable": false
      }
    ]
  },
  {
    "id": "forest",
    "zones": {
      "air": [
        [
          15,
          85,
          10,
          35
        ]
      ],
      "ground": [
        [
          8,
          92,
          64,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "squirrel",
        "zones": [
          "ground"
        ],
        "aspect": 0.996,
        "flippable": true
      },
      {
        "id": "rabbit",
        "zones": [
          "ground"
        ],
        "aspect": 0.546,
        "flippable": false
      },
      {
        "id": "mushroom",
        "zones": [
          "ground"
        ],
        "aspect": 0.871,
        "flippable": false
      },
      {
        "id": "acorn",
        "zones": [
          "ground"
        ],
        "aspect": 1.0,
        "flippable": false
      },
      {
        "id": "fox",
        "zones": [
          "ground"
        ],
        "aspect": 0.921,
        "flippable": true
      },
      {
        "id": "owl",
        "zones": [
          "air"
        ],
        "aspect": 0.654,
        "flippable": false
      },
      {
        "id": "butterfly",
        "zones": [
          "air"
        ],
        "aspect": 1.034,
        "flippable": false
      },
      {
        "id": "bluebird",
        "zones": [
          "air"
        ],
        "aspect": 1.165,
        "flippable": true
      },
      {
        "id": "hedgehog",
        "zones": [
          "ground"
        ],
        "aspect": 1.257,
        "flippable": true
      },
      {
        "id": "pinecone",
        "zones": [
          "ground"
        ],
        "aspect": 0.754,
        "flippable": false
      },
      {
        "id": "deer",
        "zones": [
          "ground"
        ],
        "aspect": 0.721,
        "flippable": true
      },
      {
        "id": "bear",
        "zones": [
          "ground"
        ],
        "aspect": 0.767,
        "flippable": false
      },
      {
        "id": "leaf",
        "zones": [
          "air",
          "ground"
        ],
        "aspect": 0.858,
        "flippable": false
      },
      {
        "id": "log",
        "zones": [
          "ground"
        ],
        "aspect": 1.086,
        "flippable": false
      },
      {
        "id": "woodpecker",
        "zones": [
          "air"
        ],
        "aspect": 0.821,
        "flippable": true
      }
    ]
  },
  {
    "id": "park",
    "zones": {
      "sky": [
        [
          20,
          85,
          6,
          28
        ]
      ],
      "lawn": [
        [
          6,
          94,
          60,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "kite",
        "zones": [
          "sky"
        ],
        "aspect": 0.946,
        "flippable": false
      },
      {
        "id": "balloon",
        "zones": [
          "sky",
          "lawn"
        ],
        "aspect": 0.396,
        "flippable": false
      },
      {
        "id": "soccerball",
        "zones": [
          "lawn"
        ],
        "aspect": 0.979,
        "flippable": false
      },
      {
        "id": "dog",
        "zones": [
          "lawn"
        ],
        "aspect": 0.846,
        "flippable": true
      },
      {
        "id": "tricycle",
        "zones": [
          "lawn"
        ],
        "aspect": 1.171,
        "flippable": true
      },
      {
        "id": "pigeon",
        "zones": [
          "lawn"
        ],
        "aspect": 0.971,
        "flippable": true
      },
      {
        "id": "tulip",
        "zones": [
          "lawn"
        ],
        "aspect": 0.521,
        "flippable": false
      },
      {
        "id": "shovel",
        "zones": [
          "lawn"
        ],
        "aspect": 0.863,
        "flippable": true
      },
      {
        "id": "frisbee",
        "zones": [
          "sky",
          "lawn"
        ],
        "aspect": 0.996,
        "flippable": false
      },
      {
        "id": "duck",
        "zones": [
          "lawn"
        ],
        "aspect": 0.896,
        "flippable": true
      },
      {
        "id": "bench",
        "zones": [
          "lawn"
        ],
        "aspect": 1.206,
        "flippable": false
      },
      {
        "id": "jumprope",
        "zones": [
          "lawn"
        ],
        "aspect": 0.742,
        "flippable": false
      },
      {
        "id": "cat",
        "zones": [
          "lawn"
        ],
        "aspect": 0.812,
        "flippable": false
      },
      {
        "id": "butterfly",
        "zones": [
          "sky",
          "lawn"
        ],
        "aspect": 1.538,
        "flippable": false
      },
      {
        "id": "icecream",
        "zones": [
          "lawn"
        ],
        "aspect": 0.408,
        "flippable": false
      }
    ]
  },
  {
    "id": "kitchen",
    "zones": {
      "shelf": [
        [
          4,
          26,
          31,
          38
        ]
      ],
      "counter": [
        [
          4,
          40,
          53,
          59
        ],
        [
          46,
          74,
          52,
          57
        ]
      ],
      "floor": [
        [
          6,
          94,
          78,
          94
        ]
      ]
    },
    "sprites": [
      {
        "id": "apple",
        "zones": [
          "counter",
          "shelf"
        ],
        "aspect": 0.887,
        "flippable": false
      },
      {
        "id": "banana",
        "zones": [
          "counter"
        ],
        "aspect": 0.629,
        "flippable": true
      },
      {
        "id": "cup",
        "zones": [
          "counter",
          "shelf"
        ],
        "aspect": 0.912,
        "flippable": true
      },
      {
        "id": "pot",
        "zones": [
          "counter",
          "floor"
        ],
        "aspect": 1.048,
        "flippable": false
      },
      {
        "id": "pan",
        "zones": [
          "counter"
        ],
        "aspect": 1.739,
        "flippable": true
      },
      {
        "id": "carrot",
        "zones": [
          "counter"
        ],
        "aspect": 0.354,
        "flippable": false
      },
      {
        "id": "teapot",
        "zones": [
          "counter",
          "shelf"
        ],
        "aspect": 1.371,
        "flippable": true
      },
      {
        "id": "bread",
        "zones": [
          "counter",
          "shelf"
        ],
        "aspect": 1.356,
        "flippable": false
      },
      {
        "id": "egg",
        "zones": [
          "counter"
        ],
        "aspect": 0.787,
        "flippable": false
      },
      {
        "id": "milk",
        "zones": [
          "counter",
          "shelf",
          "floor"
        ],
        "aspect": 0.396,
        "flippable": false
      },
      {
        "id": "strawberry",
        "zones": [
          "counter",
          "shelf"
        ],
        "aspect": 0.771,
        "flippable": false
      },
      {
        "id": "spoon",
        "zones": [
          "counter"
        ],
        "aspect": 0.279,
        "flippable": false
      },
      {
        "id": "kettle",
        "zones": [
          "counter",
          "shelf"
        ],
        "aspect": 1.048,
        "flippable": true
      },
      {
        "id": "cheese",
        "zones": [
          "counter"
        ],
        "aspect": 1.29,
        "flippable": true
      },
      {
        "id": "tomato",
        "zones": [
          "counter",
          "shelf"
        ],
        "aspect": 0.946,
        "flippable": false
      }
    ]
  },
  {
    "id": "kidsroom",
    "zones": {
      "shelf": [
        [
          28,
          41,
          32,
          44
        ],
        [
          3,
          18,
          48,
          55
        ]
      ],
      "floor": [
        [
          6,
          94,
          75,
          94
        ],
        [
          22,
          66,
          67,
          75
        ]
      ]
    },
    "sprites": [
      {
        "id": "teddybear",
        "zones": [
          "floor",
          "shelf"
        ],
        "aspect": 0.696,
        "flippable": false
      },
      {
        "id": "ball",
        "zones": [
          "floor"
        ],
        "aspect": 0.979,
        "flippable": false
      },
      {
        "id": "toycar",
        "zones": [
          "floor",
          "shelf"
        ],
        "aspect": 0.846,
        "flippable": true
      },
      {
        "id": "book",
        "zones": [
          "floor",
          "shelf"
        ],
        "aspect": 0.829,
        "flippable": false
      },
      {
        "id": "blocks",
        "zones": [
          "floor"
        ],
        "aspect": 0.658,
        "flippable": false
      },
      {
        "id": "rocket",
        "zones": [
          "floor",
          "shelf"
        ],
        "aspect": 1.086,
        "flippable": false
      },
      {
        "id": "xylophone",
        "zones": [
          "floor"
        ],
        "aspect": 1.446,
        "flippable": false
      },
      {
        "id": "clock",
        "zones": [
          "shelf"
        ],
        "aspect": 0.912,
        "flippable": false
      },
      {
        "id": "robot",
        "zones": [
          "floor",
          "shelf"
        ],
        "aspect": 0.662,
        "flippable": false
      },
      {
        "id": "duckie",
        "zones": [
          "floor",
          "shelf"
        ],
        "aspect": 0.912,
        "flippable": true
      },
      {
        "id": "drum",
        "zones": [
          "floor"
        ],
        "aspect": 0.754,
        "flippable": false
      },
      {
        "id": "train",
        "zones": [
          "floor",
          "shelf"
        ],
        "aspect": 1.42,
        "flippable": true
      },
      {
        "id": "doll",
        "zones": [
          "floor",
          "shelf"
        ],
        "aspect": 0.537,
        "flippable": false
      },
      {
        "id": "kite",
        "zones": [
          "floor"
        ],
        "aspect": 0.858,
        "flippable": false
      },
      {
        "id": "pencilcase",
        "zones": [
          "shelf",
          "floor"
        ],
        "aspect": 0.979,
        "flippable": false
      }
    ]
  },
  {
    "id": "meadow",
    "zones": {
      "sky": [
        [
          8,
          92,
          8,
          30
        ]
      ],
      "grass": [
        [
          6,
          94,
          62,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "ladybug",
        "zones": [
          "grass"
        ],
        "aspect": 0.892,
        "flippable": true
      },
      {
        "id": "bee",
        "zones": [
          "sky",
          "grass"
        ],
        "aspect": 0.879,
        "flippable": false
      },
      {
        "id": "sunflower",
        "zones": [
          "grass"
        ],
        "aspect": 0.787,
        "flippable": false
      },
      {
        "id": "snail",
        "zones": [
          "grass"
        ],
        "aspect": 1.283,
        "flippable": true
      },
      {
        "id": "frog",
        "zones": [
          "grass"
        ],
        "aspect": 0.883,
        "flippable": false
      },
      {
        "id": "dragonfly",
        "zones": [
          "sky"
        ],
        "aspect": 0.996,
        "flippable": false
      },
      {
        "id": "butterfly",
        "zones": [
          "sky",
          "grass"
        ],
        "aspect": 1.395,
        "flippable": false
      },
      {
        "id": "mushroom",
        "zones": [
          "grass"
        ],
        "aspect": 0.958,
        "flippable": false
      },
      {
        "id": "daisy",
        "zones": [
          "grass"
        ],
        "aspect": 1.0,
        "flippable": false
      },
      {
        "id": "caterpillar",
        "zones": [
          "grass"
        ],
        "aspect": 1.678,
        "flippable": true
      },
      {
        "id": "rabbit",
        "zones": [
          "grass"
        ],
        "aspect": 0.521,
        "flippable": false
      },
      {
        "id": "bird",
        "zones": [
          "sky"
        ],
        "aspect": 1.076,
        "flippable": true
      },
      {
        "id": "tulip",
        "zones": [
          "grass"
        ],
        "aspect": 0.746,
        "flippable": false
      },
      {
        "id": "clover",
        "zones": [
          "grass"
        ],
        "aspect": 0.829,
        "flippable": false
      },
      {
        "id": "ant",
        "zones": [
          "grass"
        ],
        "aspect": 1.017,
        "flippable": true
      }
    ]
  },
  {
    "id": "nightsky",
    "zones": {
      "sky": [
        [
          8,
          92,
          6,
          40
        ]
      ],
      "hill": [
        [
          8,
          92,
          72,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "star",
        "zones": [
          "sky"
        ],
        "aspect": 1.043,
        "flippable": false
      },
      {
        "id": "moon",
        "zones": [
          "sky"
        ],
        "aspect": 0.967,
        "flippable": false
      },
      {
        "id": "rocket",
        "zones": [
          "sky"
        ],
        "aspect": 0.721,
        "flippable": true
      },
      {
        "id": "planet",
        "zones": [
          "sky"
        ],
        "aspect": 1.212,
        "flippable": false
      },
      {
        "id": "comet",
        "zones": [
          "sky"
        ],
        "aspect": 0.783,
        "flippable": true
      },
      {
        "id": "satellite",
        "zones": [
          "sky"
        ],
        "aspect": 0.971,
        "flippable": false
      },
      {
        "id": "cloud",
        "zones": [
          "sky"
        ],
        "aspect": 1.667,
        "flippable": false
      },
      {
        "id": "owl",
        "zones": [
          "hill"
        ],
        "aspect": 0.704,
        "flippable": false
      },
      {
        "id": "bat",
        "zones": [
          "sky"
        ],
        "aspect": 1.529,
        "flippable": false
      },
      {
        "id": "airplane",
        "zones": [
          "sky"
        ],
        "aspect": 1.021,
        "flippable": true
      },
      {
        "id": "ufo",
        "zones": [
          "sky"
        ],
        "aspect": 2.0,
        "flippable": false
      },
      {
        "id": "shootingstar",
        "zones": [
          "sky"
        ],
        "aspect": 0.912,
        "flippable": true
      },
      {
        "id": "lantern",
        "zones": [
          "hill"
        ],
        "aspect": 0.637,
        "flippable": false
      },
      {
        "id": "cat",
        "zones": [
          "hill"
        ],
        "aspect": 0.625,
        "flippable": true
      },
      {
        "id": "smallplanet",
        "zones": [
          "sky"
        ],
        "aspect": 0.979,
        "flippable": false
      }
    ]
  },
  {
    "id": "town",
    "zones": {
      "sky": [
        [
          10,
          85,
          6,
          24
        ]
      ],
      "street": [
        [
          8,
          92,
          66,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "car",
        "zones": [
          "street"
        ],
        "aspect": 2.162,
        "flippable": true
      },
      {
        "id": "bus",
        "zones": [
          "street"
        ],
        "aspect": 1.048,
        "flippable": true
      },
      {
        "id": "bicycle",
        "zones": [
          "street"
        ],
        "aspect": 0.917,
        "flippable": true
      },
      {
        "id": "mailbox",
        "zones": [
          "street"
        ],
        "aspect": 0.662,
        "flippable": true
      },
      {
        "id": "cat",
        "zones": [
          "street"
        ],
        "aspect": 0.696,
        "flippable": true
      },
      {
        "id": "dog",
        "zones": [
          "street"
        ],
        "aspect": 0.721,
        "flippable": false
      },
      {
        "id": "bird",
        "zones": [
          "sky"
        ],
        "aspect": 1.218,
        "flippable": true
      },
      {
        "id": "balloon",
        "zones": [
          "sky"
        ],
        "aspect": 0.508,
        "flippable": false
      },
      {
        "id": "taxi",
        "zones": [
          "street"
        ],
        "aspect": 1.905,
        "flippable": true
      },
      {
        "id": "trafficcone",
        "zones": [
          "street"
        ],
        "aspect": 0.758,
        "flippable": false
      },
      {
        "id": "truck",
        "zones": [
          "street"
        ],
        "aspect": 1.832,
        "flippable": true
      },
      {
        "id": "scooter",
        "zones": [
          "street"
        ],
        "aspect": 0.938,
        "flippable": true
      },
      {
        "id": "bench",
        "zones": [
          "street"
        ],
        "aspect": 0.992,
        "flippable": false
      },
      {
        "id": "pigeon",
        "zones": [
          "street"
        ],
        "aspect": 0.908,
        "flippable": true
      },
      {
        "id": "umbrella",
        "zones": [
          "street"
        ],
        "aspect": 0.904,
        "flippable": true
      }
    ]
  },
  {
    "id": "zoo",
    "zones": {
      "ground": [
        [
          6,
          94,
          58,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "elephant",
        "zones": [
          "ground"
        ],
        "aspect": 1.111,
        "flippable": true
      },
      {
        "id": "giraffe",
        "zones": [
          "ground"
        ],
        "aspect": 0.383,
        "flippable": true
      },
      {
        "id": "lion",
        "zones": [
          "ground"
        ],
        "aspect": 0.7,
        "flippable": false
      },
      {
        "id": "panda",
        "zones": [
          "ground"
        ],
        "aspect": 0.725,
        "flippable": false
      },
      {
        "id": "penguin",
        "zones": [
          "ground"
        ],
        "aspect": 0.683,
        "flippable": true
      },
      {
        "id": "monkey",
        "zones": [
          "ground"
        ],
        "aspect": 0.8,
        "flippable": false
      },
      {
        "id": "zebra",
        "zones": [
          "ground"
        ],
        "aspect": 0.629,
        "flippable": true
      },
      {
        "id": "flamingo",
        "zones": [
          "ground"
        ],
        "aspect": 0.912,
        "flippable": true
      },
      {
        "id": "hippo",
        "zones": [
          "ground"
        ],
        "aspect": 0.896,
        "flippable": false
      },
      {
        "id": "kangaroo",
        "zones": [
          "ground"
        ],
        "aspect": 0.713,
        "flippable": true
      },
      {
        "id": "koala",
        "zones": [
          "ground"
        ],
        "aspect": 0.883,
        "flippable": false
      },
      {
        "id": "rhino",
        "zones": [
          "ground"
        ],
        "aspect": 1.137,
        "flippable": true
      },
      {
        "id": "bear",
        "zones": [
          "ground"
        ],
        "aspect": 0.758,
        "flippable": false
      },
      {
        "id": "parrot",
        "zones": [
          "ground"
        ],
        "aspect": 0.821,
        "flippable": true
      },
      {
        "id": "seal",
        "zones": [
          "ground"
        ],
        "aspect": 1.579,
        "flippable": true
      }
    ]
  },
  {
    "id": "farm",
    "zones": {
      "sky": [
        [
          8,
          92,
          6,
          20
        ]
      ],
      "pasture": [
        [
          6,
          94,
          62,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "cow",
        "zones": [
          "pasture"
        ],
        "aspect": 0.838,
        "flippable": false
      },
      {
        "id": "pig",
        "zones": [
          "pasture"
        ],
        "aspect": 0.879,
        "flippable": false
      },
      {
        "id": "sheep",
        "zones": [
          "pasture"
        ],
        "aspect": 0.854,
        "flippable": false
      },
      {
        "id": "horse",
        "zones": [
          "pasture"
        ],
        "aspect": 0.604,
        "flippable": true
      },
      {
        "id": "chicken",
        "zones": [
          "pasture"
        ],
        "aspect": 0.996,
        "flippable": true
      },
      {
        "id": "chick",
        "zones": [
          "pasture"
        ],
        "aspect": 0.892,
        "flippable": true
      },
      {
        "id": "goat",
        "zones": [
          "pasture"
        ],
        "aspect": 0.625,
        "flippable": true
      },
      {
        "id": "tractor",
        "zones": [
          "pasture"
        ],
        "aspect": 1.121,
        "flippable": true
      },
      {
        "id": "haybale",
        "zones": [
          "pasture"
        ],
        "aspect": 0.983,
        "flippable": false
      },
      {
        "id": "milkcan",
        "zones": [
          "pasture"
        ],
        "aspect": 0.779,
        "flippable": false
      },
      {
        "id": "duck",
        "zones": [
          "pasture"
        ],
        "aspect": 0.821,
        "flippable": true
      },
      {
        "id": "dog",
        "zones": [
          "pasture"
        ],
        "aspect": 0.729,
        "flippable": true
      },
      {
        "id": "carrot",
        "zones": [
          "pasture"
        ],
        "aspect": 0.396,
        "flippable": false
      },
      {
        "id": "basket",
        "zones": [
          "pasture"
        ],
        "aspect": 1.048,
        "flippable": false
      },
      {
        "id": "crow",
        "zones": [
          "sky"
        ],
        "aspect": 1.2,
        "flippable": true
      }
    ]
  },
  {
    "id": "garden",
    "zones": {
      "sky": [
        [
          22,
          76,
          5,
          20
        ]
      ],
      "lawn": [
        [
          4,
          96,
          70,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "wateringcan",
        "zones": [
          "lawn"
        ],
        "aspect": 1.048,
        "flippable": true
      },
      {
        "id": "flowerpot",
        "zones": [
          "lawn"
        ],
        "aspect": 0.654,
        "flippable": false
      },
      {
        "id": "snail",
        "zones": [
          "lawn"
        ],
        "aspect": 1.154,
        "flippable": true
      },
      {
        "id": "ladybug",
        "zones": [
          "lawn"
        ],
        "aspect": 1.0,
        "flippable": false
      },
      {
        "id": "butterfly",
        "zones": [
          "sky",
          "lawn"
        ],
        "aspect": 1.304,
        "flippable": false
      },
      {
        "id": "bee",
        "zones": [
          "sky",
          "lawn"
        ],
        "aspect": 1.127,
        "flippable": false
      },
      {
        "id": "bird",
        "zones": [
          "lawn",
          "sky"
        ],
        "aspect": 1.165,
        "flippable": true
      },
      {
        "id": "gnome",
        "zones": [
          "lawn"
        ],
        "aspect": 0.838,
        "flippable": false
      },
      {
        "id": "hose",
        "zones": [
          "lawn"
        ],
        "aspect": 0.954,
        "flippable": false
      },
      {
        "id": "rake",
        "zones": [
          "lawn"
        ],
        "aspect": 0.388,
        "flippable": false
      },
      {
        "id": "sunflower",
        "zones": [
          "lawn"
        ],
        "aspect": 0.654,
        "flippable": false
      },
      {
        "id": "wheelbarrow",
        "zones": [
          "lawn"
        ],
        "aspect": 1.548,
        "flippable": true
      },
      {
        "id": "cat",
        "zones": [
          "lawn"
        ],
        "aspect": 1.048,
        "flippable": false
      },
      {
        "id": "birdhouse",
        "zones": [
          "lawn"
        ],
        "aspect": 0.979,
        "flippable": false
      },
      {
        "id": "tomatoplant",
        "zones": [
          "lawn"
        ],
        "aspect": 0.517,
        "flippable": false
      }
    ]
  },
  {
    "id": "river",
    "zones": {
      "sky": [
        [
          8,
          92,
          6,
          22
        ]
      ],
      "river": [
        [
          42,
          84,
          46,
          54
        ],
        [
          12,
          70,
          70,
          86
        ]
      ],
      "bank": [
        [
          4,
          38,
          55,
          63
        ],
        [
          80,
          96,
          66,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "fish",
        "zones": [
          "river"
        ],
        "aspect": 1.116,
        "flippable": true
      },
      {
        "id": "frog",
        "zones": [
          "bank"
        ],
        "aspect": 1.25,
        "flippable": false
      },
      {
        "id": "duck",
        "zones": [
          "river",
          "bank"
        ],
        "aspect": 0.804,
        "flippable": true
      },
      {
        "id": "boat",
        "zones": [
          "river"
        ],
        "aspect": 1.714,
        "flippable": true
      },
      {
        "id": "turtle",
        "zones": [
          "bank"
        ],
        "aspect": 1.062,
        "flippable": true
      },
      {
        "id": "dragonfly",
        "zones": [
          "sky"
        ],
        "aspect": 0.9,
        "flippable": false
      },
      {
        "id": "fishingrod",
        "zones": [
          "bank"
        ],
        "aspect": 0.688,
        "flippable": false
      },
      {
        "id": "bucket",
        "zones": [
          "bank"
        ],
        "aspect": 0.863,
        "flippable": false
      },
      {
        "id": "heron",
        "zones": [
          "bank"
        ],
        "aspect": 0.779,
        "flippable": true
      },
      {
        "id": "lilypad",
        "zones": [
          "river"
        ],
        "aspect": 1.27,
        "flippable": false
      },
      {
        "id": "crab",
        "zones": [
          "bank"
        ],
        "aspect": 1.176,
        "flippable": false
      },
      {
        "id": "otter",
        "zones": [
          "bank",
          "river"
        ],
        "aspect": 0.896,
        "flippable": true
      },
      {
        "id": "stone",
        "zones": [
          "bank"
        ],
        "aspect": 1.29,
        "flippable": false
      },
      {
        "id": "kingfisher",
        "zones": [
          "sky"
        ],
        "aspect": 0.846,
        "flippable": true
      },
      {
        "id": "leaf",
        "zones": [
          "river",
          "bank"
        ],
        "aspect": 0.671,
        "flippable": false
      }
    ]
  },
  {
    "id": "snowfield",
    "zones": {
      "sky": [
        [
          20,
          80,
          6,
          26
        ]
      ],
      "snow": [
        [
          6,
          94,
          64,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "snowman",
        "zones": [
          "snow"
        ],
        "aspect": 0.713,
        "flippable": false
      },
      {
        "id": "sled",
        "zones": [
          "snow"
        ],
        "aspect": 1.678,
        "flippable": false
      },
      {
        "id": "penguin",
        "zones": [
          "snow"
        ],
        "aspect": 0.754,
        "flippable": true
      },
      {
        "id": "mitten",
        "zones": [
          "snow"
        ],
        "aspect": 0.704,
        "flippable": true
      },
      {
        "id": "cocoa",
        "zones": [
          "snow"
        ],
        "aspect": 0.904,
        "flippable": false
      },
      {
        "id": "skis",
        "zones": [
          "snow"
        ],
        "aspect": 0.713,
        "flippable": false
      },
      {
        "id": "polarbear",
        "zones": [
          "snow"
        ],
        "aspect": 0.838,
        "flippable": false
      },
      {
        "id": "fox",
        "zones": [
          "snow"
        ],
        "aspect": 0.787,
        "flippable": true
      },
      {
        "id": "rabbit",
        "zones": [
          "snow"
        ],
        "aspect": 0.613,
        "flippable": true
      },
      {
        "id": "snowflake",
        "zones": [
          "sky"
        ],
        "aspect": 0.871,
        "flippable": false
      },
      {
        "id": "bird",
        "zones": [
          "sky",
          "snow"
        ],
        "aspect": 0.983,
        "flippable": true
      },
      {
        "id": "beanie",
        "zones": [
          "snow"
        ],
        "aspect": 0.804,
        "flippable": false
      },
      {
        "id": "snowball",
        "zones": [
          "snow"
        ],
        "aspect": 1.472,
        "flippable": false
      },
      {
        "id": "firtree",
        "zones": [
          "snow"
        ],
        "aspect": 1.106,
        "flippable": false
      },
      {
        "id": "boots",
        "zones": [
          "snow"
        ],
        "aspect": 0.929,
        "flippable": true
      }
    ]
  },
  {
    "id": "underwater",
    "zones": {
      "water": [
        [
          12,
          88,
          36,
          64
        ]
      ],
      "seabed": [
        [
          12,
          88,
          76,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "clownfish",
        "zones": [
          "water"
        ],
        "aspect": 1.148,
        "flippable": true
      },
      {
        "id": "jellyfish",
        "zones": [
          "water"
        ],
        "aspect": 0.704,
        "flippable": false
      },
      {
        "id": "seahorse",
        "zones": [
          "water"
        ],
        "aspect": 0.517,
        "flippable": true
      },
      {
        "id": "turtle",
        "zones": [
          "water"
        ],
        "aspect": 1.127,
        "flippable": true
      },
      {
        "id": "octopus",
        "zones": [
          "water",
          "seabed"
        ],
        "aspect": 0.946,
        "flippable": false
      },
      {
        "id": "starfish",
        "zones": [
          "seabed"
        ],
        "aspect": 0.925,
        "flippable": false
      },
      {
        "id": "shell",
        "zones": [
          "seabed"
        ],
        "aspect": 1.067,
        "flippable": false
      },
      {
        "id": "crab",
        "zones": [
          "seabed"
        ],
        "aspect": 1.429,
        "flippable": false
      },
      {
        "id": "whale",
        "zones": [
          "water"
        ],
        "aspect": 1.727,
        "flippable": true
      },
      {
        "id": "dolphin",
        "zones": [
          "water"
        ],
        "aspect": 0.979,
        "flippable": true
      },
      {
        "id": "pufferfish",
        "zones": [
          "water"
        ],
        "aspect": 1.218,
        "flippable": true
      },
      {
        "id": "treasure",
        "zones": [
          "seabed"
        ],
        "aspect": 0.838,
        "flippable": false
      },
      {
        "id": "anchor",
        "zones": [
          "seabed"
        ],
        "aspect": 0.975,
        "flippable": false
      },
      {
        "id": "submarine",
        "zones": [
          "water"
        ],
        "aspect": 1.702,
        "flippable": true
      },
      {
        "id": "shark",
        "zones": [
          "water"
        ],
        "aspect": 1.548,
        "flippable": true
      }
    ]
  },
  {
    "id": "space",
    "zones": {
      "space": [
        [
          8,
          92,
          8,
          40
        ]
      ],
      "surface": [
        [
          4,
          40,
          72,
          92
        ],
        [
          62,
          96,
          70,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "rocket",
        "zones": [
          "space"
        ],
        "aspect": 0.446,
        "flippable": true
      },
      {
        "id": "astronaut",
        "zones": [
          "space",
          "surface"
        ],
        "aspect": 1.067,
        "flippable": false
      },
      {
        "id": "planet",
        "zones": [
          "space"
        ],
        "aspect": 0.996,
        "flippable": false
      },
      {
        "id": "moon",
        "zones": [
          "space"
        ],
        "aspect": 0.983,
        "flippable": true
      },
      {
        "id": "star",
        "zones": [
          "space"
        ],
        "aspect": 1.004,
        "flippable": false
      },
      {
        "id": "satellite",
        "zones": [
          "space"
        ],
        "aspect": 1.655,
        "flippable": false
      },
      {
        "id": "ufo",
        "zones": [
          "space"
        ],
        "aspect": 1.86,
        "flippable": false
      },
      {
        "id": "comet",
        "zones": [
          "space"
        ],
        "aspect": 0.921,
        "flippable": true
      },
      {
        "id": "alien",
        "zones": [
          "surface"
        ],
        "aspect": 0.787,
        "flippable": false
      },
      {
        "id": "rover",
        "zones": [
          "surface"
        ],
        "aspect": 1.034,
        "flippable": true
      },
      {
        "id": "flag",
        "zones": [
          "surface"
        ],
        "aspect": 0.475,
        "flippable": true
      },
      {
        "id": "meteor",
        "zones": [
          "space"
        ],
        "aspect": 0.975,
        "flippable": true
      },
      {
        "id": "telescope",
        "zones": [
          "surface"
        ],
        "aspect": 0.896,
        "flippable": true
      },
      {
        "id": "earth",
        "zones": [
          "space"
        ],
        "aspect": 0.988,
        "flippable": false
      },
      {
        "id": "spacestation",
        "zones": [
          "space"
        ],
        "aspect": 1.096,
        "flippable": false
      }
    ]
  },
  {
    "id": "station",
    "zones": {
      "sky": [
        [
          10,
          90,
          6,
          22
        ]
      ],
      "platform": [
        [
          4,
          45,
          62,
          90
        ],
        [
          45,
          70,
          58,
          66
        ]
      ],
      "track": [
        [
          55,
          90,
          72,
          86
        ]
      ]
    },
    "sprites": [
      {
        "id": "train",
        "zones": [
          "track"
        ],
        "aspect": 1.69,
        "flippable": true
      },
      {
        "id": "suitcase",
        "zones": [
          "platform"
        ],
        "aspect": 1.333,
        "flippable": true
      },
      {
        "id": "clock",
        "zones": [
          "sky"
        ],
        "aspect": 0.958,
        "flippable": false
      },
      {
        "id": "bench",
        "zones": [
          "platform"
        ],
        "aspect": 1.714,
        "flippable": false
      },
      {
        "id": "ticket",
        "zones": [
          "platform"
        ],
        "aspect": 1.655,
        "flippable": true
      },
      {
        "id": "backpack",
        "zones": [
          "platform"
        ],
        "aspect": 0.767,
        "flippable": false
      },
      {
        "id": "pigeon",
        "zones": [
          "platform"
        ],
        "aspect": 0.908,
        "flippable": true
      },
      {
        "id": "umbrella",
        "zones": [
          "platform"
        ],
        "aspect": 1.067,
        "flippable": true
      },
      {
        "id": "bottle",
        "zones": [
          "platform"
        ],
        "aspect": 0.362,
        "flippable": false
      },
      {
        "id": "dog",
        "zones": [
          "platform"
        ],
        "aspect": 0.963,
        "flippable": true
      },
      {
        "id": "bento",
        "zones": [
          "platform"
        ],
        "aspect": 1.034,
        "flippable": false
      },
      {
        "id": "sign",
        "zones": [
          "platform"
        ],
        "aspect": 0.621,
        "flippable": false
      },
      {
        "id": "trashcan",
        "zones": [
          "platform"
        ],
        "aspect": 0.654,
        "flippable": false
      },
      {
        "id": "balloon",
        "zones": [
          "sky",
          "platform"
        ],
        "aspect": 0.521,
        "flippable": false
      },
      {
        "id": "camera",
        "zones": [
          "platform"
        ],
        "aspect": 1.311,
        "flippable": false
      }
    ]
  },
  {
    "id": "supermarket",
    "zones": {
      "shelf": [
        [
          3,
          28,
          24,
          52
        ],
        [
          72,
          96,
          20,
          56
        ],
        [
          34,
          66,
          40,
          52
        ]
      ],
      "floor": [
        [
          20,
          80,
          70,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "cart",
        "zones": [
          "floor"
        ],
        "aspect": 0.896,
        "flippable": true
      },
      {
        "id": "basket",
        "zones": [
          "floor"
        ],
        "aspect": 1.053,
        "flippable": false
      },
      {
        "id": "milk",
        "zones": [
          "shelf"
        ],
        "aspect": 0.708,
        "flippable": false
      },
      {
        "id": "bread",
        "zones": [
          "shelf"
        ],
        "aspect": 1.412,
        "flippable": false
      },
      {
        "id": "apple",
        "zones": [
          "shelf"
        ],
        "aspect": 0.887,
        "flippable": false
      },
      {
        "id": "banana",
        "zones": [
          "shelf"
        ],
        "aspect": 0.883,
        "flippable": true
      },
      {
        "id": "watermelon",
        "zones": [
          "floor",
          "shelf"
        ],
        "aspect": 0.846,
        "flippable": false
      },
      {
        "id": "cereal",
        "zones": [
          "shelf"
        ],
        "aspect": 0.758,
        "flippable": false
      },
      {
        "id": "juice",
        "zones": [
          "shelf"
        ],
        "aspect": 0.375,
        "flippable": false
      },
      {
        "id": "eggs",
        "zones": [
          "shelf"
        ],
        "aspect": 1.039,
        "flippable": false
      },
      {
        "id": "carrot",
        "zones": [
          "shelf"
        ],
        "aspect": 1.004,
        "flippable": false
      },
      {
        "id": "fish",
        "zones": [
          "shelf"
        ],
        "aspect": 0.971,
        "flippable": true
      },
      {
        "id": "cheese",
        "zones": [
          "shelf"
        ],
        "aspect": 1.212,
        "flippable": true
      },
      {
        "id": "grapes",
        "zones": [
          "shelf"
        ],
        "aspect": 0.833,
        "flippable": false
      },
      {
        "id": "candy",
        "zones": [
          "shelf"
        ],
        "aspect": 0.979,
        "flippable": false
      }
    ]
  },
  {
    "id": "classroom",
    "zones": {
      "board": [
        [
          40,
          63,
          36,
          48
        ],
        [
          36,
          70,
          18,
          30
        ]
      ],
      "floor": [
        [
          10,
          90,
          68,
          94
        ]
      ]
    },
    "sprites": [
      {
        "id": "globe",
        "zones": [
          "floor"
        ],
        "aspect": 0.996,
        "flippable": false
      },
      {
        "id": "backpack",
        "zones": [
          "floor"
        ],
        "aspect": 0.812,
        "flippable": false
      },
      {
        "id": "book",
        "zones": [
          "floor"
        ],
        "aspect": 0.771,
        "flippable": false
      },
      {
        "id": "pencil",
        "zones": [
          "floor"
        ],
        "aspect": 0.167,
        "flippable": false
      },
      {
        "id": "magnet",
        "zones": [
          "floor"
        ],
        "aspect": 0.975,
        "flippable": false
      },
      {
        "id": "eraser",
        "zones": [
          "floor"
        ],
        "aspect": 1.159,
        "flippable": true
      },
      {
        "id": "sharpener",
        "zones": [
          "board"
        ],
        "aspect": 1.412,
        "flippable": false
      },
      {
        "id": "clock",
        "zones": [
          "board"
        ],
        "aspect": 0.975,
        "flippable": false
      },
      {
        "id": "scissors",
        "zones": [
          "floor"
        ],
        "aspect": 0.921,
        "flippable": true
      },
      {
        "id": "apple",
        "zones": [
          "floor"
        ],
        "aspect": 0.912,
        "flippable": false
      },
      {
        "id": "crayons",
        "zones": [
          "floor"
        ],
        "aspect": 0.954,
        "flippable": false
      },
      {
        "id": "notebook",
        "zones": [
          "floor"
        ],
        "aspect": 0.892,
        "flippable": true
      },
      {
        "id": "plant",
        "zones": [
          "floor"
        ],
        "aspect": 0.725,
        "flippable": false
      },
      {
        "id": "hamster",
        "zones": [
          "floor"
        ],
        "aspect": 0.879,
        "flippable": true
      },
      {
        "id": "abacus",
        "zones": [
          "floor"
        ],
        "aspect": 0.863,
        "flippable": false
      }
    ]
  },
  {
    "id": "bathroom",
    "zones": {
      "shelf": [
        [
          80,
          92,
          26,
          48
        ]
      ],
      "bath": [
        [
          10,
          38,
          42,
          52
        ],
        [
          80,
          96,
          48,
          56
        ]
      ],
      "floor": [
        [
          30,
          78,
          66,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "duck",
        "zones": [
          "bath",
          "shelf"
        ],
        "aspect": 0.867,
        "flippable": true
      },
      {
        "id": "soap",
        "zones": [
          "shelf",
          "bath"
        ],
        "aspect": 1.69,
        "flippable": false
      },
      {
        "id": "toothbrush",
        "zones": [
          "shelf"
        ],
        "aspect": 0.267,
        "flippable": true
      },
      {
        "id": "towel",
        "zones": [
          "shelf",
          "floor"
        ],
        "aspect": 0.85,
        "flippable": false
      },
      {
        "id": "shampoo",
        "zones": [
          "shelf",
          "floor"
        ],
        "aspect": 0.517,
        "flippable": false
      },
      {
        "id": "sponge",
        "zones": [
          "bath",
          "floor"
        ],
        "aspect": 0.921,
        "flippable": false
      },
      {
        "id": "bubbles",
        "zones": [
          "bath"
        ],
        "aspect": 0.908,
        "flippable": false
      },
      {
        "id": "comb",
        "zones": [
          "shelf"
        ],
        "aspect": 0.613,
        "flippable": true
      },
      {
        "id": "cup",
        "zones": [
          "shelf"
        ],
        "aspect": 1.039,
        "flippable": true
      },
      {
        "id": "boat",
        "zones": [
          "bath"
        ],
        "aspect": 1.121,
        "flippable": true
      },
      {
        "id": "fish",
        "zones": [
          "bath"
        ],
        "aspect": 1.257,
        "flippable": true
      },
      {
        "id": "mirror",
        "zones": [
          "shelf"
        ],
        "aspect": 0.963,
        "flippable": false
      },
      {
        "id": "slippers",
        "zones": [
          "floor"
        ],
        "aspect": 1.404,
        "flippable": true
      },
      {
        "id": "bucket",
        "zones": [
          "floor"
        ],
        "aspect": 0.954,
        "flippable": false
      },
      {
        "id": "toothpaste",
        "zones": [
          "shelf"
        ],
        "aspect": 0.421,
        "flippable": false
      }
    ]
  },
  {
    "id": "picnic",
    "zones": {
      "sky": [
        [
          8,
          92,
          6,
          22
        ]
      ],
      "grass": [
        [
          6,
          94,
          62,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "basket",
        "zones": [
          "grass"
        ],
        "aspect": 0.983,
        "flippable": false
      },
      {
        "id": "sandwich",
        "zones": [
          "grass"
        ],
        "aspect": 1.356,
        "flippable": false
      },
      {
        "id": "riceball",
        "zones": [
          "grass"
        ],
        "aspect": 1.111,
        "flippable": false
      },
      {
        "id": "juice",
        "zones": [
          "grass"
        ],
        "aspect": 0.942,
        "flippable": true
      },
      {
        "id": "apple",
        "zones": [
          "grass"
        ],
        "aspect": 0.833,
        "flippable": false
      },
      {
        "id": "cupcake",
        "zones": [
          "grass"
        ],
        "aspect": 0.708,
        "flippable": false
      },
      {
        "id": "ant",
        "zones": [
          "grass"
        ],
        "aspect": 0.704,
        "flippable": true
      },
      {
        "id": "butterfly",
        "zones": [
          "sky",
          "grass"
        ],
        "aspect": 1.27,
        "flippable": false
      },
      {
        "id": "ball",
        "zones": [
          "grass"
        ],
        "aspect": 1.106,
        "flippable": false
      },
      {
        "id": "hat",
        "zones": [
          "grass"
        ],
        "aspect": 1.437,
        "flippable": false
      },
      {
        "id": "thermos",
        "zones": [
          "grass"
        ],
        "aspect": 0.421,
        "flippable": false
      },
      {
        "id": "banana",
        "zones": [
          "grass"
        ],
        "aspect": 0.75,
        "flippable": true
      },
      {
        "id": "kite",
        "zones": [
          "sky"
        ],
        "aspect": 0.792,
        "flippable": false
      },
      {
        "id": "dog",
        "zones": [
          "grass"
        ],
        "aspect": 0.742,
        "flippable": true
      },
      {
        "id": "bird",
        "zones": [
          "sky",
          "grass"
        ],
        "aspect": 0.871,
        "flippable": true
      }
    ]
  },
  {
    "id": "camp",
    "zones": {
      "sky": [
        [
          12,
          88,
          6,
          22
        ]
      ],
      "ground": [
        [
          6,
          94,
          66,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "tent",
        "zones": [
          "ground"
        ],
        "aspect": 1.341,
        "flippable": true
      },
      {
        "id": "campfire",
        "zones": [
          "ground"
        ],
        "aspect": 1.053,
        "flippable": false
      },
      {
        "id": "mug",
        "zones": [
          "ground"
        ],
        "aspect": 1.257,
        "flippable": false
      },
      {
        "id": "backpack",
        "zones": [
          "ground"
        ],
        "aspect": 0.758,
        "flippable": false
      },
      {
        "id": "marshmallow",
        "zones": [
          "ground"
        ],
        "aspect": 0.454,
        "flippable": false
      },
      {
        "id": "kettle",
        "zones": [
          "ground"
        ],
        "aspect": 0.842,
        "flippable": true
      },
      {
        "id": "flashlight",
        "zones": [
          "ground"
        ],
        "aspect": 0.433,
        "flippable": false
      },
      {
        "id": "owl",
        "zones": [
          "sky"
        ],
        "aspect": 0.775,
        "flippable": false
      },
      {
        "id": "raccoon",
        "zones": [
          "ground"
        ],
        "aspect": 0.858,
        "flippable": true
      },
      {
        "id": "binoculars",
        "zones": [
          "ground"
        ],
        "aspect": 1.071,
        "flippable": false
      },
      {
        "id": "chair",
        "zones": [
          "ground"
        ],
        "aspect": 0.725,
        "flippable": true
      },
      {
        "id": "boots",
        "zones": [
          "ground"
        ],
        "aspect": 1.143,
        "flippable": true
      },
      {
        "id": "firefly",
        "zones": [
          "sky"
        ],
        "aspect": 0.988,
        "flippable": false
      },
      {
        "id": "fish",
        "zones": [
          "ground"
        ],
        "aspect": 0.954,
        "flippable": true
      },
      {
        "id": "compass",
        "zones": [
          "ground"
        ],
        "aspect": 1.091,
        "flippable": false
      }
    ]
  },
  {
    "id": "rainyday",
    "zones": {
      "sky": [
        [
          12,
          88,
          4,
          20
        ]
      ],
      "street": [
        [
          6,
          94,
          62,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "umbrella",
        "zones": [
          "street"
        ],
        "aspect": 1.067,
        "flippable": false
      },
      {
        "id": "raincoat",
        "zones": [
          "street"
        ],
        "aspect": 0.617,
        "flippable": false
      },
      {
        "id": "boots",
        "zones": [
          "street"
        ],
        "aspect": 0.825,
        "flippable": true
      },
      {
        "id": "frog",
        "zones": [
          "street"
        ],
        "aspect": 0.996,
        "flippable": false
      },
      {
        "id": "snail",
        "zones": [
          "street"
        ],
        "aspect": 1.356,
        "flippable": true
      },
      {
        "id": "puddle",
        "zones": [
          "street"
        ],
        "aspect": 1.509,
        "flippable": false
      },
      {
        "id": "car",
        "zones": [
          "street"
        ],
        "aspect": 1.805,
        "flippable": true
      },
      {
        "id": "cat",
        "zones": [
          "street"
        ],
        "aspect": 0.688,
        "flippable": false
      },
      {
        "id": "rainbow",
        "zones": [
          "sky"
        ],
        "aspect": 1.371,
        "flippable": false
      },
      {
        "id": "cloud",
        "zones": [
          "sky"
        ],
        "aspect": 1.805,
        "flippable": false
      },
      {
        "id": "hydrangea",
        "zones": [
          "street"
        ],
        "aspect": 0.904,
        "flippable": false
      },
      {
        "id": "duck",
        "zones": [
          "street"
        ],
        "aspect": 0.871,
        "flippable": true
      },
      {
        "id": "bucket",
        "zones": [
          "street"
        ],
        "aspect": 0.746,
        "flippable": false
      },
      {
        "id": "teruteru",
        "zones": [
          "sky"
        ],
        "aspect": 0.979,
        "flippable": false
      },
      {
        "id": "bicycle",
        "zones": [
          "street"
        ],
        "aspect": 1.333,
        "flippable": true
      }
    ]
  },
  {
    "id": "autumn",
    "zones": {
      "sky": [
        [
          15,
          85,
          4,
          22
        ]
      ],
      "ground": [
        [
          6,
          94,
          66,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "maple",
        "zones": [
          "ground",
          "sky"
        ],
        "aspect": 0.896,
        "flippable": false
      },
      {
        "id": "acorn",
        "zones": [
          "ground"
        ],
        "aspect": 0.767,
        "flippable": false
      },
      {
        "id": "grapes",
        "zones": [
          "ground"
        ],
        "aspect": 0.929,
        "flippable": false
      },
      {
        "id": "mushroom",
        "zones": [
          "ground"
        ],
        "aspect": 0.754,
        "flippable": false
      },
      {
        "id": "squirrel",
        "zones": [
          "ground"
        ],
        "aspect": 0.858,
        "flippable": true
      },
      {
        "id": "persimmon",
        "zones": [
          "ground"
        ],
        "aspect": 0.958,
        "flippable": false
      },
      {
        "id": "sweetpotato",
        "zones": [
          "ground"
        ],
        "aspect": 0.667,
        "flippable": false
      },
      {
        "id": "basket",
        "zones": [
          "ground"
        ],
        "aspect": 0.963,
        "flippable": false
      },
      {
        "id": "dragonfly",
        "zones": [
          "sky"
        ],
        "aspect": 1.231,
        "flippable": false
      },
      {
        "id": "ginkgo",
        "zones": [
          "ground",
          "sky"
        ],
        "aspect": 1.004,
        "flippable": false
      },
      {
        "id": "hedgehog",
        "zones": [
          "ground"
        ],
        "aspect": 1.062,
        "flippable": true
      },
      {
        "id": "pumpkin",
        "zones": [
          "ground"
        ],
        "aspect": 0.938,
        "flippable": false
      },
      {
        "id": "leaves",
        "zones": [
          "ground"
        ],
        "aspect": 1.026,
        "flippable": false
      },
      {
        "id": "bird",
        "zones": [
          "sky"
        ],
        "aspect": 0.892,
        "flippable": true
      },
      {
        "id": "rake",
        "zones": [
          "ground"
        ],
        "aspect": 0.883,
        "flippable": true
      }
    ]
  },
  {
    "id": "birthday",
    "zones": {
      "wall": [
        [
          12,
          40,
          32,
          46
        ],
        [
          60,
          88,
          30,
          44
        ]
      ],
      "table": [
        [
          30,
          62,
          56,
          62
        ],
        [
          76,
          90,
          56,
          60
        ]
      ],
      "floor": [
        [
          6,
          94,
          76,
          94
        ]
      ]
    },
    "sprites": [
      {
        "id": "cake",
        "zones": [
          "table"
        ],
        "aspect": 1.283,
        "flippable": false
      },
      {
        "id": "present",
        "zones": [
          "table",
          "floor"
        ],
        "aspect": 0.954,
        "flippable": false
      },
      {
        "id": "balloon",
        "zones": [
          "wall"
        ],
        "aspect": 0.629,
        "flippable": false
      },
      {
        "id": "partyhat",
        "zones": [
          "table"
        ],
        "aspect": 0.833,
        "flippable": false
      },
      {
        "id": "cupcake",
        "zones": [
          "table"
        ],
        "aspect": 0.717,
        "flippable": false
      },
      {
        "id": "candy",
        "zones": [
          "table"
        ],
        "aspect": 0.742,
        "flippable": false
      },
      {
        "id": "juice",
        "zones": [
          "table"
        ],
        "aspect": 0.596,
        "flippable": true
      },
      {
        "id": "teddybear",
        "zones": [
          "floor"
        ],
        "aspect": 0.783,
        "flippable": false
      },
      {
        "id": "cracker",
        "zones": [
          "table"
        ],
        "aspect": 0.725,
        "flippable": false
      },
      {
        "id": "card",
        "zones": [
          "table"
        ],
        "aspect": 0.9,
        "flippable": false
      },
      {
        "id": "star",
        "zones": [
          "wall"
        ],
        "aspect": 1.076,
        "flippable": false
      },
      {
        "id": "icecream",
        "zones": [
          "table"
        ],
        "aspect": 0.537,
        "flippable": false
      },
      {
        "id": "donut",
        "zones": [
          "table"
        ],
        "aspect": 1.004,
        "flippable": false
      },
      {
        "id": "toycar",
        "zones": [
          "floor"
        ],
        "aspect": 1.92,
        "flippable": true
      },
      {
        "id": "candle",
        "zones": [
          "table"
        ],
        "aspect": 0.421,
        "flippable": false
      }
    ]
  },
  {
    "id": "bakery",
    "zones": {
      "shelf": [
        [
          3,
          24,
          22,
          46
        ],
        [
          74,
          96,
          24,
          52
        ]
      ],
      "counter": [
        [
          8,
          34,
          53,
          58
        ],
        [
          36,
          66,
          55,
          59
        ],
        [
          68,
          94,
          58,
          64
        ]
      ]
    },
    "sprites": [
      {
        "id": "croissant",
        "zones": [
          "shelf",
          "counter"
        ],
        "aspect": 0.992,
        "flippable": true
      },
      {
        "id": "baguette",
        "zones": [
          "shelf"
        ],
        "aspect": 0.608,
        "flippable": true
      },
      {
        "id": "donut",
        "zones": [
          "counter",
          "shelf"
        ],
        "aspect": 0.983,
        "flippable": false
      },
      {
        "id": "melonpan",
        "zones": [
          "shelf",
          "counter"
        ],
        "aspect": 1.013,
        "flippable": false
      },
      {
        "id": "cake",
        "zones": [
          "counter"
        ],
        "aspect": 0.988,
        "flippable": true
      },
      {
        "id": "cookie",
        "zones": [
          "counter",
          "shelf"
        ],
        "aspect": 0.979,
        "flippable": false
      },
      {
        "id": "muffin",
        "zones": [
          "shelf",
          "counter"
        ],
        "aspect": 0.863,
        "flippable": false
      },
      {
        "id": "pretzel",
        "zones": [
          "shelf"
        ],
        "aspect": 1.076,
        "flippable": false
      },
      {
        "id": "tray",
        "zones": [
          "counter"
        ],
        "aspect": 1.081,
        "flippable": false
      },
      {
        "id": "tongs",
        "zones": [
          "counter"
        ],
        "aspect": 1.148,
        "flippable": true
      },
      {
        "id": "bag",
        "zones": [
          "counter"
        ],
        "aspect": 0.892,
        "flippable": false
      },
      {
        "id": "pie",
        "zones": [
          "shelf"
        ],
        "aspect": 1.034,
        "flippable": false
      },
      {
        "id": "jam",
        "zones": [
          "shelf"
        ],
        "aspect": 0.625,
        "flippable": false
      },
      {
        "id": "rollingpin",
        "zones": [
          "counter"
        ],
        "aspect": 0.95,
        "flippable": true
      },
      {
        "id": "loaf",
        "zones": [
          "shelf"
        ],
        "aspect": 1.491,
        "flippable": true
      }
    ]
  },
  {
    "id": "toyshop",
    "zones": {
      "shelf": [
        [
          4,
          28,
          26,
          58
        ],
        [
          72,
          96,
          28,
          62
        ],
        [
          40,
          66,
          40,
          56
        ]
      ],
      "floor": [
        [
          20,
          80,
          68,
          94
        ]
      ]
    },
    "sprites": [
      {
        "id": "teddybear",
        "zones": [
          "shelf",
          "floor"
        ],
        "aspect": 0.704,
        "flippable": false
      },
      {
        "id": "robot",
        "zones": [
          "shelf"
        ],
        "aspect": 0.662,
        "flippable": false
      },
      {
        "id": "train",
        "zones": [
          "floor"
        ],
        "aspect": 2.162,
        "flippable": true
      },
      {
        "id": "ball",
        "zones": [
          "floor"
        ],
        "aspect": 1.026,
        "flippable": false
      },
      {
        "id": "doll",
        "zones": [
          "shelf"
        ],
        "aspect": 0.604,
        "flippable": false
      },
      {
        "id": "trumpet",
        "zones": [
          "shelf"
        ],
        "aspect": 2.105,
        "flippable": false
      },
      {
        "id": "kite",
        "zones": [
          "shelf"
        ],
        "aspect": 0.704,
        "flippable": false
      },
      {
        "id": "blocks",
        "zones": [
          "floor"
        ],
        "aspect": 1.067,
        "flippable": false
      },
      {
        "id": "rockinghorse",
        "zones": [
          "floor"
        ],
        "aspect": 0.762,
        "flippable": true
      },
      {
        "id": "car",
        "zones": [
          "shelf",
          "floor"
        ],
        "aspect": 1.0,
        "flippable": true
      },
      {
        "id": "drum",
        "zones": [
          "floor"
        ],
        "aspect": 0.746,
        "flippable": false
      },
      {
        "id": "puzzle",
        "zones": [
          "shelf"
        ],
        "aspect": 1.096,
        "flippable": false
      },
      {
        "id": "airplane",
        "zones": [
          "shelf"
        ],
        "aspect": 2.0,
        "flippable": true
      },
      {
        "id": "dinosaur",
        "zones": [
          "shelf",
          "floor"
        ],
        "aspect": 0.879,
        "flippable": true
      },
      {
        "id": "top",
        "zones": [
          "shelf"
        ],
        "aspect": 0.992,
        "flippable": false
      }
    ]
  },
  {
    "id": "pond",
    "zones": {
      "sky": [
        [
          12,
          88,
          6,
          22
        ]
      ],
      "pond": [
        [
          22,
          80,
          48,
          68
        ]
      ],
      "grass": [
        [
          6,
          94,
          80,
          94
        ]
      ]
    },
    "sprites": [
      {
        "id": "duck",
        "zones": [
          "pond"
        ],
        "aspect": 0.838,
        "flippable": true
      },
      {
        "id": "frog",
        "zones": [
          "pond"
        ],
        "aspect": 1.137,
        "flippable": false
      },
      {
        "id": "carp",
        "zones": [
          "pond"
        ],
        "aspect": 0.821,
        "flippable": true
      },
      {
        "id": "lilypad",
        "zones": [
          "pond"
        ],
        "aspect": 1.206,
        "flippable": false
      },
      {
        "id": "lotus",
        "zones": [
          "pond"
        ],
        "aspect": 1.655,
        "flippable": false
      },
      {
        "id": "turtle",
        "zones": [
          "grass"
        ],
        "aspect": 1.0,
        "flippable": true
      },
      {
        "id": "dragonfly",
        "zones": [
          "sky"
        ],
        "aspect": 1.257,
        "flippable": false
      },
      {
        "id": "boat",
        "zones": [
          "pond"
        ],
        "aspect": 1.6,
        "flippable": false
      },
      {
        "id": "heron",
        "zones": [
          "grass"
        ],
        "aspect": 0.604,
        "flippable": true
      },
      {
        "id": "reed",
        "zones": [
          "grass"
        ],
        "aspect": 0.879,
        "flippable": false
      },
      {
        "id": "snail",
        "zones": [
          "grass"
        ],
        "aspect": 1.043,
        "flippable": true
      },
      {
        "id": "swan",
        "zones": [
          "pond"
        ],
        "aspect": 1.034,
        "flippable": true
      },
      {
        "id": "net",
        "zones": [
          "grass"
        ],
        "aspect": 0.871,
        "flippable": false
      },
      {
        "id": "butterfly",
        "zones": [
          "sky"
        ],
        "aspect": 1.437,
        "flippable": false
      },
      {
        "id": "stone",
        "zones": [
          "grass"
        ],
        "aspect": 1.057,
        "flippable": false
      }
    ]
  },
  {
    "id": "jungle",
    "zones": {
      "canopy": [
        [
          15,
          85,
          10,
          32
        ]
      ],
      "ground": [
        [
          6,
          94,
          64,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "monkey",
        "zones": [
          "canopy",
          "ground"
        ],
        "aspect": 0.954,
        "flippable": false
      },
      {
        "id": "parrot",
        "zones": [
          "canopy"
        ],
        "aspect": 0.771,
        "flippable": true
      },
      {
        "id": "toucan",
        "zones": [
          "canopy"
        ],
        "aspect": 0.958,
        "flippable": true
      },
      {
        "id": "tiger",
        "zones": [
          "ground"
        ],
        "aspect": 0.988,
        "flippable": false
      },
      {
        "id": "elephant",
        "zones": [
          "ground"
        ],
        "aspect": 1.021,
        "flippable": true
      },
      {
        "id": "snake",
        "zones": [
          "ground"
        ],
        "aspect": 0.662,
        "flippable": true
      },
      {
        "id": "frog",
        "zones": [
          "ground"
        ],
        "aspect": 1.008,
        "flippable": false
      },
      {
        "id": "butterfly",
        "zones": [
          "canopy"
        ],
        "aspect": 1.341,
        "flippable": false
      },
      {
        "id": "pineapple",
        "zones": [
          "ground",
          "canopy"
        ],
        "aspect": 0.604,
        "flippable": false
      },
      {
        "id": "sloth",
        "zones": [
          "canopy"
        ],
        "aspect": 0.875,
        "flippable": false
      },
      {
        "id": "chameleon",
        "zones": [
          "ground"
        ],
        "aspect": 1.297,
        "flippable": true
      },
      {
        "id": "gorilla",
        "zones": [
          "ground"
        ],
        "aspect": 0.6,
        "flippable": false
      },
      {
        "id": "flower",
        "zones": [
          "ground"
        ],
        "aspect": 0.787,
        "flippable": false
      },
      {
        "id": "coconut",
        "zones": [
          "ground"
        ],
        "aspect": 0.887,
        "flippable": false
      },
      {
        "id": "crocodile",
        "zones": [
          "ground"
        ],
        "aspect": 1.067,
        "flippable": true
      }
    ]
  },
  {
    "id": "airport",
    "zones": {
      "sky": [
        [
          8,
          92,
          6,
          30
        ]
      ],
      "tarmac": [
        [
          6,
          94,
          64,
          92
        ]
      ]
    },
    "sprites": [
      {
        "id": "airplane",
        "zones": [
          "sky",
          "tarmac"
        ],
        "aspect": 2.526,
        "flippable": true
      },
      {
        "id": "jet",
        "zones": [
          "sky"
        ],
        "aspect": 1.404,
        "flippable": true
      },
      {
        "id": "helicopter",
        "zones": [
          "sky"
        ],
        "aspect": 2.069,
        "flippable": true
      },
      {
        "id": "suitcase",
        "zones": [
          "tarmac"
        ],
        "aspect": 0.846,
        "flippable": false
      },
      {
        "id": "cart",
        "zones": [
          "tarmac"
        ],
        "aspect": 1.021,
        "flippable": true
      },
      {
        "id": "fueltruck",
        "zones": [
          "tarmac"
        ],
        "aspect": 0.988,
        "flippable": true
      },
      {
        "id": "cone",
        "zones": [
          "tarmac"
        ],
        "aspect": 0.575,
        "flippable": false
      },
      {
        "id": "windsock",
        "zones": [
          "tarmac"
        ],
        "aspect": 0.296,
        "flippable": true
      },
      {
        "id": "bird",
        "zones": [
          "sky"
        ],
        "aspect": 1.039,
        "flippable": true
      },
      {
        "id": "cloud",
        "zones": [
          "sky"
        ],
        "aspect": 1.206,
        "flippable": false
      },
      {
        "id": "bus",
        "zones": [
          "tarmac"
        ],
        "aspect": 0.917,
        "flippable": true
      },
      {
        "id": "balloon",
        "zones": [
          "sky"
        ],
        "aspect": 0.617,
        "flippable": false
      },
      {
        "id": "propplane",
        "zones": [
          "tarmac"
        ],
        "aspect": 1.5,
        "flippable": true
      },
      {
        "id": "sunglasses",
        "zones": [
          "tarmac"
        ],
        "aspect": 2.222,
        "flippable": false
      },
      {
        "id": "tractor",
        "zones": [
          "tarmac"
        ],
        "aspect": 1.333,
        "flippable": true
      }
    ]
  },
  {
    "id": "construction",
    "zones": {
      "sky": [
        [
          4,
          28,
          6,
          22
        ],
        [
          60,
          96,
          6,
          22
        ]
      ],
      "ground": [
        [
          6,
          94,
          70,
          94
        ],
        [
          4,
          28,
          58,
          70
        ]
      ]
    },
    "sprites": [
      {
        "id": "excavator",
        "zones": [
          "ground"
        ],
        "aspect": 0.863,
        "flippable": true
      },
      {
        "id": "dumptruck",
        "zones": [
          "ground"
        ],
        "aspect": 1.589,
        "flippable": true
      },
      {
        "id": "bulldozer",
        "zones": [
          "ground"
        ],
        "aspect": 1.509,
        "flippable": true
      },
      {
        "id": "cone",
        "zones": [
          "ground"
        ],
        "aspect": 1.057,
        "flippable": false
      },
      {
        "id": "drill",
        "zones": [
          "ground"
        ],
        "aspect": 1.03,
        "flippable": true
      },
      {
        "id": "shovel",
        "zones": [
          "ground"
        ],
        "aspect": 0.371,
        "flippable": false
      },
      {
        "id": "bricks",
        "zones": [
          "ground"
        ],
        "aspect": 0.817,
        "flippable": false
      },
      {
        "id": "wheelbarrow",
        "zones": [
          "ground"
        ],
        "aspect": 1.206,
        "flippable": true
      },
      {
        "id": "mixer",
        "zones": [
          "ground"
        ],
        "aspect": 1.437,
        "flippable": true
      },
      {
        "id": "hammer",
        "zones": [
          "ground"
        ],
        "aspect": 0.825,
        "flippable": true
      },
      {
        "id": "ladder",
        "zones": [
          "ground"
        ],
        "aspect": 0.696,
        "flippable": false
      },
      {
        "id": "barrier",
        "zones": [
          "ground"
        ],
        "aspect": 1.319,
        "flippable": false
      },
      {
        "id": "pipe",
        "zones": [
          "ground"
        ],
        "aspect": 0.708,
        "flippable": false
      },
      {
        "id": "toolbox",
        "zones": [
          "ground"
        ],
        "aspect": 1.053,
        "flippable": false
      },
      {
        "id": "bird",
        "zones": [
          "sky"
        ],
        "aspect": 0.9,
        "flippable": true
      }
    ]
  }
]
