export interface WordEntry {
  id: string
  word: string
  translationJa: string
  category:
    | 'animal'
    | 'food'
    | 'nature'
    | 'color'
    | 'vehicle'
    | 'clothing'
    | 'household'
    | 'school'
    | 'weather'
    | 'bodyPart'
    | 'toy'
    | 'sport'
    | 'instrument'
    | 'shape'
    | 'place'
}

export const wordBank: WordEntry[] = [
  { id: 'dog', word: 'dog', translationJa: 'いぬ', category: 'animal' },
  { id: 'cat', word: 'cat', translationJa: 'ねこ', category: 'animal' },
  { id: 'bird', word: 'bird', translationJa: 'とり', category: 'animal' },
  { id: 'fish', word: 'fish', translationJa: 'さかな', category: 'animal' },
  { id: 'rabbit', word: 'rabbit', translationJa: 'うさぎ', category: 'animal' },
  { id: 'bear', word: 'bear', translationJa: 'くま', category: 'animal' },
  { id: 'elephant', word: 'elephant', translationJa: 'ぞう', category: 'animal' },
  { id: 'lion', word: 'lion', translationJa: 'らいおん', category: 'animal' },
  { id: 'horse', word: 'horse', translationJa: 'うま', category: 'animal' },
  { id: 'cow', word: 'cow', translationJa: 'うし', category: 'animal' },
  { id: 'pig', word: 'pig', translationJa: 'ぶた', category: 'animal' },
  { id: 'sheep', word: 'sheep', translationJa: 'ひつじ', category: 'animal' },
  { id: 'duck', word: 'duck', translationJa: 'あひる', category: 'animal' },
  { id: 'chicken', word: 'chicken', translationJa: 'にわとり', category: 'animal' },
  { id: 'frog', word: 'frog', translationJa: 'かえる', category: 'animal' },
  { id: 'turtle', word: 'turtle', translationJa: 'かめ', category: 'animal' },
  { id: 'penguin', word: 'penguin', translationJa: 'ぺんぎん', category: 'animal' },
  { id: 'monkey', word: 'monkey', translationJa: 'さる', category: 'animal' },
  { id: 'tiger', word: 'tiger', translationJa: 'とら', category: 'animal' },
  { id: 'zebra', word: 'zebra', translationJa: 'しまうま', category: 'animal' },
  { id: 'giraffe', word: 'giraffe', translationJa: 'きりん', category: 'animal' },
  { id: 'panda', word: 'panda', translationJa: 'ぱんだ', category: 'animal' },
  { id: 'koala', word: 'koala', translationJa: 'こあら', category: 'animal' },
  { id: 'fox', word: 'fox', translationJa: 'きつね', category: 'animal' },
  { id: 'owl', word: 'owl', translationJa: 'ふくろう', category: 'animal' },
  { id: 'butterfly', word: 'butterfly', translationJa: 'ちょう', category: 'animal' },
  { id: 'bee', word: 'bee', translationJa: 'はち', category: 'animal' },
  { id: 'ladybug', word: 'ladybug', translationJa: 'てんとうむし', category: 'animal' },
  { id: 'snail', word: 'snail', translationJa: 'かたつむり', category: 'animal' },
  { id: 'squirrel', word: 'squirrel', translationJa: 'りす', category: 'animal' },
  { id: 'hedgehog', word: 'hedgehog', translationJa: 'はりねずみ', category: 'animal' },
  { id: 'deer', word: 'deer', translationJa: 'しか', category: 'animal' },
  { id: 'kangaroo', word: 'kangaroo', translationJa: 'かんがるー', category: 'animal' },
  { id: 'apple', word: 'apple', translationJa: 'りんご', category: 'food' },
  { id: 'banana', word: 'banana', translationJa: 'バナナ', category: 'food' },
  { id: 'grape', word: 'grape', translationJa: 'ぶどう', category: 'food' },
  { id: 'strawberry', word: 'strawberry', translationJa: 'いちご', category: 'food' },
  { id: 'orange', word: 'orange', translationJa: 'オレンジ', category: 'food' },
  { id: 'watermelon', word: 'watermelon', translationJa: 'すいか', category: 'food' },
  { id: 'bread', word: 'bread', translationJa: 'パン', category: 'food' },
  { id: 'egg', word: 'egg', translationJa: 'たまご', category: 'food' },
  { id: 'cake', word: 'cake', translationJa: 'ケーキ', category: 'food' },
  { id: 'pizza', word: 'pizza', translationJa: 'ぴざ', category: 'food' },
  { id: 'hamburger', word: 'hamburger', translationJa: 'はんばーがー', category: 'food' },
  { id: 'hotdog', word: 'hotdog', translationJa: 'ほっとどっぐ', category: 'food' },
  { id: 'rice', word: 'rice', translationJa: 'ごはん', category: 'food' },
  { id: 'noodles', word: 'noodles', translationJa: 'めん', category: 'food' },
  { id: 'sushi', word: 'sushi', translationJa: 'すし', category: 'food' },
  { id: 'cookie', word: 'cookie', translationJa: 'くっきー', category: 'food' },
  { id: 'donut', word: 'donut', translationJa: 'どーなつ', category: 'food' },
  { id: 'icecream', word: 'ice cream', translationJa: 'あいすくりーむ', category: 'food' },
  { id: 'milk', word: 'milk', translationJa: 'ぎゅうにゅう', category: 'food' },
  { id: 'cheese', word: 'cheese', translationJa: 'ちーず', category: 'food' },
  { id: 'carrot', word: 'carrot', translationJa: 'にんじん', category: 'food' },
  { id: 'tomato', word: 'tomato', translationJa: 'とまと', category: 'food' },
  { id: 'potato', word: 'potato', translationJa: 'じゃがいも', category: 'food' },
  { id: 'corn', word: 'corn', translationJa: 'とうもろこし', category: 'food' },
  { id: 'broccoli', word: 'broccoli', translationJa: 'ぶろっこりー', category: 'food' },
  { id: 'mushroom', word: 'mushroom', translationJa: 'きのこ', category: 'food' },
  { id: 'pineapple', word: 'pineapple', translationJa: 'ぱいなっぷる', category: 'food' },
  { id: 'peach', word: 'peach', translationJa: 'もも', category: 'food' },
  { id: 'lemon', word: 'lemon', translationJa: 'れもん', category: 'food' },
  { id: 'sun', word: 'sun', translationJa: 'たいよう', category: 'nature' },
  { id: 'star', word: 'star', translationJa: 'ほし', category: 'nature' },
  { id: 'heart', word: 'heart', translationJa: 'はーと', category: 'nature' },
  { id: 'moon', word: 'moon', translationJa: 'つき', category: 'nature' },
  { id: 'flower', word: 'flower', translationJa: 'はな', category: 'nature' },
  { id: 'balloon', word: 'balloon', translationJa: 'ふうせん', category: 'nature' },
  { id: 'cloud', word: 'cloud', translationJa: 'くも', category: 'nature' },
  { id: 'mountain', word: 'mountain', translationJa: 'やま', category: 'nature' },
  { id: 'tree', word: 'tree', translationJa: 'き', category: 'nature' },
  { id: 'leaf', word: 'leaf', translationJa: 'は', category: 'nature' },
  { id: 'rock', word: 'rock', translationJa: 'いし', category: 'nature' },
  { id: 'grass', word: 'grass', translationJa: 'くさ', category: 'nature' },
  { id: 'seashell', word: 'seashell', translationJa: 'かいがら', category: 'nature' },
  { id: 'pinecone', word: 'pinecone', translationJa: 'まつぼっくり', category: 'nature' },
  { id: 'acorn', word: 'acorn', translationJa: 'どんぐり', category: 'nature' },
  { id: 'cactus', word: 'cactus', translationJa: 'さぼてん', category: 'nature' },
  { id: 'rainbow', word: 'rainbow', translationJa: 'にじ', category: 'nature' },
  { id: 'coconut', word: 'coconut', translationJa: 'やしのみ', category: 'nature' },
  { id: 'red', word: 'red', translationJa: 'あか', category: 'color' },
  { id: 'blue', word: 'blue', translationJa: 'あお', category: 'color' },
  { id: 'yellow', word: 'yellow', translationJa: 'きいろ', category: 'color' },
  { id: 'green', word: 'green', translationJa: 'みどり', category: 'color' },
  { id: 'purple', word: 'purple', translationJa: 'むらさき', category: 'color' },
  { id: 'pink', word: 'pink', translationJa: 'ピンク', category: 'color' },
  { id: 'brown', word: 'brown', translationJa: 'ちゃいろ', category: 'color' },
  { id: 'black', word: 'black', translationJa: 'くろ', category: 'color' },
  { id: 'car', word: 'car', translationJa: 'くるま', category: 'vehicle' },
  { id: 'bus', word: 'bus', translationJa: 'バス', category: 'vehicle' },
  { id: 'train', word: 'train', translationJa: 'でんしゃ', category: 'vehicle' },
  { id: 'airplane', word: 'airplane', translationJa: 'ひこうき', category: 'vehicle' },
  { id: 'bicycle', word: 'bicycle', translationJa: 'じてんしゃ', category: 'vehicle' },
  { id: 'boat', word: 'boat', translationJa: 'ふね', category: 'vehicle' },
  { id: 'ship', word: 'ship', translationJa: 'せんぱく', category: 'vehicle' },
  { id: 'motorcycle', word: 'motorcycle', translationJa: 'おーとばい', category: 'vehicle' },
  { id: 'helicopter', word: 'helicopter', translationJa: 'へりこぷたー', category: 'vehicle' },
  { id: 'truck', word: 'truck', translationJa: 'とらっく', category: 'vehicle' },
  { id: 'tractor', word: 'tractor', translationJa: 'とらくたー', category: 'vehicle' },
  { id: 'scooter', word: 'scooter', translationJa: 'すくーたー', category: 'vehicle' },
  // harder/exotic animals
  { id: 'sloth', word: 'sloth', translationJa: 'なまけもの', category: 'animal' },
  { id: 'macaw', word: 'macaw', translationJa: 'こんごういんこ', category: 'animal' },
  { id: 'chameleon', word: 'chameleon', translationJa: 'かめれおん', category: 'animal' },
  { id: 'platypus', word: 'platypus', translationJa: 'かものはし', category: 'animal' },
  { id: 'wombat', word: 'wombat', translationJa: 'うぉんばっと', category: 'animal' },
  { id: 'ostrich', word: 'ostrich', translationJa: 'だちょう', category: 'animal' },
  { id: 'hippopotamus', word: 'hippopotamus', translationJa: 'かば', category: 'animal' },
  { id: 'rhinoceros', word: 'rhinoceros', translationJa: 'さい', category: 'animal' },
  { id: 'octopus', word: 'octopus', translationJa: 'たこ', category: 'animal' },
  { id: 'jellyfish', word: 'jellyfish', translationJa: 'くらげ', category: 'animal' },
  { id: 'flamingo', word: 'flamingo', translationJa: 'ふらみんご', category: 'animal' },
  { id: 'raccoon', word: 'raccoon', translationJa: 'あらいぐま', category: 'animal' },
  { id: 'otter', word: 'otter', translationJa: 'かわうそ', category: 'animal' },
  { id: 'walrus', word: 'walrus', translationJa: 'せいうち', category: 'animal' },
  { id: 'porcupine', word: 'porcupine', translationJa: 'やまあらし', category: 'animal' },
  { id: 'chimpanzee', word: 'chimpanzee', translationJa: 'ちんぱんじー', category: 'animal' },
  { id: 'gorilla', word: 'gorilla', translationJa: 'ごりら', category: 'animal' },
  { id: 'cheetah', word: 'cheetah', translationJa: 'ちーたー', category: 'animal' },
  { id: 'leopard', word: 'leopard', translationJa: 'ひょう', category: 'animal' },
  { id: 'hyena', word: 'hyena', translationJa: 'はいえな', category: 'animal' },
  { id: 'crocodile', word: 'crocodile', translationJa: 'わに', category: 'animal' },
  { id: 'alligator', word: 'alligator', translationJa: 'アリゲーター', category: 'animal' },
  { id: 'iguana', word: 'iguana', translationJa: 'いぐあな', category: 'animal' },
  { id: 'scorpion', word: 'scorpion', translationJa: 'さそり', category: 'animal' },
  { id: 'dragonfly', word: 'dragonfly', translationJa: 'とんぼ', category: 'animal' },
  { id: 'firefly', word: 'firefly', translationJa: 'ほたる', category: 'animal' },
  { id: 'grasshopper', word: 'grasshopper', translationJa: 'ばった', category: 'animal' },
  { id: 'caterpillar', word: 'caterpillar', translationJa: 'いもむし', category: 'animal' },
  { id: 'squid', word: 'squid', translationJa: 'いか', category: 'animal' },
  { id: 'starfish', word: 'starfish', translationJa: 'ひとで', category: 'animal' },
  { id: 'seahorse', word: 'seahorse', translationJa: 'たつのおとしご', category: 'animal' },
  { id: 'dolphin', word: 'dolphin', translationJa: 'いるか', category: 'animal' },
  { id: 'whale', word: 'whale', translationJa: 'くじら', category: 'animal' },
  { id: 'shark', word: 'shark', translationJa: 'さめ', category: 'animal' },
  { id: 'stingray', word: 'stingray', translationJa: 'えい', category: 'animal' },
  { id: 'lobster', word: 'lobster', translationJa: 'ろぶすたー', category: 'animal' },
  { id: 'crab', word: 'crab', translationJa: 'かに', category: 'animal' },
  { id: 'shrimp', word: 'shrimp', translationJa: 'えび', category: 'animal' },
  { id: 'seal', word: 'seal', translationJa: 'あざらし', category: 'animal' },
  { id: 'beaver', word: 'beaver', translationJa: 'びーばー', category: 'animal' },
  { id: 'mole', word: 'mole', translationJa: 'もぐら', category: 'animal' },
  { id: 'bat', word: 'bat', translationJa: 'こうもり', category: 'animal' },
  { id: 'skunk', word: 'skunk', translationJa: 'すかんく', category: 'animal' },
  { id: 'armadillo', word: 'armadillo', translationJa: 'あるまじろ', category: 'animal' },
  { id: 'anteater', word: 'anteater', translationJa: 'ありくい', category: 'animal' },
  { id: 'mongoose', word: 'mongoose', translationJa: 'まんぐーす', category: 'animal' },
  { id: 'meerkat', word: 'meerkat', translationJa: 'みーきゃっと', category: 'animal' },
  { id: 'lemur', word: 'lemur', translationJa: 'きつねざる', category: 'animal' },
  { id: 'tapir', word: 'tapir', translationJa: 'ばく', category: 'animal' },
  { id: 'bison', word: 'bison', translationJa: 'あめりかばいそん', category: 'animal' },
  { id: 'buffalo', word: 'buffalo', translationJa: 'ばっふぁろー', category: 'animal' },
  { id: 'moose', word: 'moose', translationJa: 'へらじか', category: 'animal' },
  { id: 'elk', word: 'elk', translationJa: 'えるく', category: 'animal' },
  { id: 'reindeer', word: 'reindeer', translationJa: 'となかい', category: 'animal' },
  { id: 'camel', word: 'camel', translationJa: 'らくだ', category: 'animal' },
  { id: 'llama', word: 'llama', translationJa: 'らま', category: 'animal' },
  { id: 'yak', word: 'yak', translationJa: 'やく', category: 'animal' },
  { id: 'goat', word: 'goat', translationJa: 'やぎ', category: 'animal' },
  { id: 'donkey', word: 'donkey', translationJa: 'ろば', category: 'animal' },
  { id: 'mule', word: 'mule', translationJa: 'らば', category: 'animal' },
  { id: 'peacock', word: 'peacock', translationJa: 'くじゃく', category: 'animal' },
  { id: 'swan', word: 'swan', translationJa: 'はくちょう', category: 'animal' },
  { id: 'goose', word: 'goose', translationJa: 'がちょう', category: 'animal' },
  { id: 'pelican', word: 'pelican', translationJa: 'ぺりかん', category: 'animal' },
  { id: 'toucan', word: 'toucan', translationJa: 'おおはしどり', category: 'animal' },
  { id: 'parrot', word: 'parrot', translationJa: 'おうむ', category: 'animal' },
  { id: 'woodpecker', word: 'woodpecker', translationJa: 'きつつき', category: 'animal' },
  { id: 'hummingbird', word: 'hummingbird', translationJa: 'はちどり', category: 'animal' },
  { id: 'eagle', word: 'eagle', translationJa: 'わし', category: 'animal' },
  { id: 'hawk', word: 'hawk', translationJa: 'たか', category: 'animal' },
  { id: 'falcon', word: 'falcon', translationJa: 'はやぶさ', category: 'animal' },
  { id: 'vulture', word: 'vulture', translationJa: 'はげわし', category: 'animal' },
  { id: 'crow', word: 'crow', translationJa: 'からす', category: 'animal' },
  { id: 'raven', word: 'raven', translationJa: 'わたりがらす', category: 'animal' },
  { id: 'magpie', word: 'magpie', translationJa: 'かささぎ', category: 'animal' },
  { id: 'robin', word: 'robin', translationJa: 'こまどり', category: 'animal' },
  { id: 'sparrow', word: 'sparrow', translationJa: 'すずめ', category: 'animal' },
  { id: 'stork', word: 'stork', translationJa: 'こうのとり', category: 'animal' },
  { id: 'heron', word: 'heron', translationJa: 'さぎ', category: 'animal' },
  { id: 'crane', word: 'crane', translationJa: 'つる', category: 'animal' },
  { id: 'quail', word: 'quail', translationJa: 'うずら', category: 'animal' },
  { id: 'turkey', word: 'turkey', translationJa: 'しちめんちょう', category: 'animal' },
  { id: 'mantis', word: 'mantis', translationJa: 'かまきり', category: 'animal' },
  { id: 'wasp', word: 'wasp', translationJa: 'すずめばち', category: 'animal' },
  { id: 'ant', word: 'ant', translationJa: 'あり', category: 'animal' },
  { id: 'spider', word: 'spider', translationJa: 'くも', category: 'animal' },
  { id: 'centipede', word: 'centipede', translationJa: 'むかで', category: 'animal' },
  { id: 'worm', word: 'worm', translationJa: 'みみず', category: 'animal' },
  // everyday food
  { id: 'pancake', word: 'pancake', translationJa: 'パンケーキ', category: 'food' },
  { id: 'sandwich', word: 'sandwich', translationJa: 'サンドイッチ', category: 'food' },
  { id: 'soup', word: 'soup', translationJa: 'スープ', category: 'food' },
  { id: 'yogurt', word: 'yogurt', translationJa: 'ヨーグルト', category: 'food' },
  { id: 'cereal', word: 'cereal', translationJa: 'シリアル', category: 'food' },
  { id: 'spaghetti', word: 'spaghetti', translationJa: 'スパゲッティ', category: 'food' },
  { id: 'salad', word: 'salad', translationJa: 'サラダ', category: 'food' },
  { id: 'butter', word: 'butter', translationJa: 'バター', category: 'food' },
  { id: 'jam', word: 'jam', translationJa: 'ジャム', category: 'food' },
  { id: 'honey', word: 'honey', translationJa: 'はちみつ', category: 'food' },
  { id: 'sugar', word: 'sugar', translationJa: 'さとう', category: 'food' },
  { id: 'salt', word: 'salt', translationJa: 'しお', category: 'food' },
  { id: 'pepper', word: 'pepper', translationJa: 'こしょう', category: 'food' },
  { id: 'ketchup', word: 'ketchup', translationJa: 'ケチャップ', category: 'food' },
  { id: 'mayonnaise', word: 'mayonnaise', translationJa: 'マヨネーズ', category: 'food' },
  { id: 'popcorn', word: 'popcorn', translationJa: 'ポップコーン', category: 'food' },
  { id: 'pretzel', word: 'pretzel', translationJa: 'プレッツェル', category: 'food' },
  { id: 'waffle', word: 'waffle', translationJa: 'ワッフル', category: 'food' },
  { id: 'muffin', word: 'muffin', translationJa: 'マフィン', category: 'food' },
  { id: 'bagel', word: 'bagel', translationJa: 'ベーグル', category: 'food' },
  { id: 'toast', word: 'toast', translationJa: 'トースト', category: 'food' },
  { id: 'omelette', word: 'omelette', translationJa: 'オムレツ', category: 'food' },
  { id: 'pasta', word: 'pasta', translationJa: 'パスタ', category: 'food' },
  { id: 'dumpling', word: 'dumpling', translationJa: 'ぎょうざ', category: 'food' },
  { id: 'taco', word: 'taco', translationJa: 'タコス', category: 'food' },
  { id: 'burrito', word: 'burrito', translationJa: 'ブリトー', category: 'food' },
  { id: 'curry', word: 'curry', translationJa: 'カレー', category: 'food' },
  { id: 'ramen', word: 'ramen', translationJa: 'ラーメン', category: 'food' },
  { id: 'udon', word: 'udon', translationJa: 'うどん', category: 'food' },
  { id: 'tofu', word: 'tofu', translationJa: 'とうふ', category: 'food' },
  { id: 'tea', word: 'tea', translationJa: 'おちゃ', category: 'food' },
  { id: 'coffee', word: 'coffee', translationJa: 'コーヒー', category: 'food' },
  { id: 'juice', word: 'juice', translationJa: 'ジュース', category: 'food' },
  { id: 'soda', word: 'soda', translationJa: 'ソーダ', category: 'food' },
  { id: 'water', word: 'water', translationJa: 'みず', category: 'food' },
  { id: 'lettuce', word: 'lettuce', translationJa: 'レタス', category: 'food' },
  { id: 'cabbage', word: 'cabbage', translationJa: 'キャベツ', category: 'food' },
  { id: 'onion', word: 'onion', translationJa: 'たまねぎ', category: 'food' },
  { id: 'garlic', word: 'garlic', translationJa: 'にんにく', category: 'food' },
  { id: 'cucumber', word: 'cucumber', translationJa: 'きゅうり', category: 'food' },
  { id: 'pumpkin', word: 'pumpkin', translationJa: 'かぼちゃ', category: 'food' },
  { id: 'eggplant', word: 'eggplant', translationJa: 'なす', category: 'food' },
  { id: 'pea', word: 'pea', translationJa: 'グリーンピース', category: 'food' },
  { id: 'bean', word: 'bean', translationJa: 'まめ', category: 'food' },
  { id: 'spinach', word: 'spinach', translationJa: 'ほうれんそう', category: 'food' },
  { id: 'celery', word: 'celery', translationJa: 'セロリ', category: 'food' },
  { id: 'radish', word: 'radish', translationJa: 'だいこん', category: 'food' },
  { id: 'ginger', word: 'ginger', translationJa: 'しょうが', category: 'food' },
  { id: 'mango', word: 'mango', translationJa: 'マンゴー', category: 'food' },
  { id: 'kiwi', word: 'kiwi', translationJa: 'キウイ', category: 'food' },
  { id: 'cherry', word: 'cherry', translationJa: 'さくらんぼ', category: 'food' },
  { id: 'blueberry', word: 'blueberry', translationJa: 'ブルーベリー', category: 'food' },
  { id: 'raspberry', word: 'raspberry', translationJa: 'ラズベリー', category: 'food' },
  { id: 'blackberry', word: 'blackberry', translationJa: 'ブラックベリー', category: 'food' },
  { id: 'melon', word: 'melon', translationJa: 'メロン', category: 'food' },
  { id: 'papaya', word: 'papaya', translationJa: 'パパイヤ', category: 'food' },
  { id: 'avocado', word: 'avocado', translationJa: 'アボカド', category: 'food' },
  { id: 'fig', word: 'fig', translationJa: 'いちじく', category: 'food' },
  { id: 'pear', word: 'pear', translationJa: 'なし', category: 'food' },
  { id: 'plum', word: 'plum', translationJa: 'すもも', category: 'food' },
  { id: 'apricot', word: 'apricot', translationJa: 'あんず', category: 'food' },
  // nature & landscape
  { id: 'volcano', word: 'volcano', translationJa: 'かざん', category: 'nature' },
  { id: 'waterfall', word: 'waterfall', translationJa: 'たき', category: 'nature' },
  { id: 'desert', word: 'desert', translationJa: 'さばく', category: 'nature' },
  { id: 'island', word: 'island', translationJa: 'しま', category: 'nature' },
  { id: 'river', word: 'river', translationJa: 'かわ', category: 'nature' },
  { id: 'lake', word: 'lake', translationJa: 'みずうみ', category: 'nature' },
  { id: 'ocean', word: 'ocean', translationJa: 'うみ', category: 'nature' },
  { id: 'forest', word: 'forest', translationJa: 'もり', category: 'nature' },
  { id: 'valley', word: 'valley', translationJa: 'たに', category: 'nature' },
  { id: 'cave', word: 'cave', translationJa: 'どうくつ', category: 'nature' },
  { id: 'cliff', word: 'cliff', translationJa: 'がけ', category: 'nature' },
  { id: 'sand', word: 'sand', translationJa: 'すな', category: 'nature' },
  { id: 'wave', word: 'wave', translationJa: 'なみ', category: 'nature' },
  { id: 'comet', word: 'comet', translationJa: 'すいせい', category: 'nature' },
  { id: 'planet', word: 'planet', translationJa: 'わくせい', category: 'nature' },
  { id: 'galaxy', word: 'galaxy', translationJa: 'ぎんが', category: 'nature' },
  { id: 'meteor', word: 'meteor', translationJa: 'りゅうせい', category: 'nature' },
  { id: 'glacier', word: 'glacier', translationJa: 'ひょうが', category: 'nature' },
  { id: 'jungle', word: 'jungle', translationJa: 'ジャングル', category: 'nature' },
  { id: 'swamp', word: 'swamp', translationJa: 'ぬま', category: 'nature' },
  { id: 'pond', word: 'pond', translationJa: 'いけ', category: 'nature' },
  { id: 'stream', word: 'stream', translationJa: 'おがわ', category: 'nature' },
  { id: 'hill', word: 'hill', translationJa: 'おか', category: 'nature' },
  { id: 'meadow', word: 'meadow', translationJa: 'そうげん', category: 'nature' },
  { id: 'pebble', word: 'pebble', translationJa: 'こいし', category: 'nature' },
  { id: 'root', word: 'root', translationJa: 'ね', category: 'nature' },
  { id: 'branch', word: 'branch', translationJa: 'えだ', category: 'nature' },
  // more colors
  { id: 'gray', word: 'gray', translationJa: 'はいいろ', category: 'color' },
  { id: 'white', word: 'white', translationJa: 'しろ', category: 'color' },
  { id: 'gold', word: 'gold', translationJa: 'きんいろ', category: 'color' },
  { id: 'silver', word: 'silver', translationJa: 'ぎんいろ', category: 'color' },
  { id: 'turquoise', word: 'turquoise', translationJa: 'ターコイズ', category: 'color' },
  { id: 'beige', word: 'beige', translationJa: 'ベージュ', category: 'color' },
  { id: 'navy', word: 'navy', translationJa: 'こんいろ', category: 'color' },
  { id: 'maroon', word: 'maroon', translationJa: 'えんじいろ', category: 'color' },
  { id: 'indigo', word: 'indigo', translationJa: 'あいいろ', category: 'color' },
  // more vehicles
  { id: 'submarine', word: 'submarine', translationJa: 'せんすいかん', category: 'vehicle' },
  { id: 'rocket', word: 'rocket', translationJa: 'ロケット', category: 'vehicle' },
  { id: 'ambulance', word: 'ambulance', translationJa: 'きゅうきゅうしゃ', category: 'vehicle' },
  { id: 'firetruck', word: 'fire truck', translationJa: 'しょうぼうしゃ', category: 'vehicle' },
  { id: 'taxi', word: 'taxi', translationJa: 'タクシー', category: 'vehicle' },
  { id: 'ferry', word: 'ferry', translationJa: 'フェリー', category: 'vehicle' },
  { id: 'canoe', word: 'canoe', translationJa: 'カヌー', category: 'vehicle' },
  { id: 'kayak', word: 'kayak', translationJa: 'カヤック', category: 'vehicle' },
  { id: 'sailboat', word: 'sailboat', translationJa: 'ヨット', category: 'vehicle' },
  { id: 'jetski', word: 'jet ski', translationJa: 'ジェットスキー', category: 'vehicle' },
  { id: 'spaceship', word: 'spaceship', translationJa: 'うちゅうせん', category: 'vehicle' },
  { id: 'tram', word: 'tram', translationJa: 'ろめんでんしゃ', category: 'vehicle' },
  { id: 'subway', word: 'subway', translationJa: 'ちかてつ', category: 'vehicle' },
  { id: 'forklift', word: 'forklift', translationJa: 'フォークリフト', category: 'vehicle' },
  { id: 'bulldozer', word: 'bulldozer', translationJa: 'ブルドーザー', category: 'vehicle' },
  { id: 'cablecar', word: 'cable car', translationJa: 'ロープウェイ', category: 'vehicle' },
  { id: 'hotairballoon', word: 'hot air balloon', translationJa: 'ねつききゅう', category: 'vehicle' },
  // clothing
  { id: 'shirt', word: 'shirt', translationJa: 'シャツ', category: 'clothing' },
  { id: 'pants', word: 'pants', translationJa: 'ずぼん', category: 'clothing' },
  { id: 'shoes', word: 'shoes', translationJa: 'くつ', category: 'clothing' },
  { id: 'hat', word: 'hat', translationJa: 'ぼうし', category: 'clothing' },
  { id: 'jacket', word: 'jacket', translationJa: 'ジャケット', category: 'clothing' },
  { id: 'dress', word: 'dress', translationJa: 'ドレス', category: 'clothing' },
  { id: 'skirt', word: 'skirt', translationJa: 'スカート', category: 'clothing' },
  { id: 'gloves', word: 'gloves', translationJa: 'てぶくろ', category: 'clothing' },
  { id: 'scarf', word: 'scarf', translationJa: 'マフラー', category: 'clothing' },
  { id: 'boots', word: 'boots', translationJa: 'ブーツ', category: 'clothing' },
  { id: 'sweater', word: 'sweater', translationJa: 'セーター', category: 'clothing' },
  { id: 'pajamas', word: 'pajamas', translationJa: 'パジャマ', category: 'clothing' },
  { id: 'umbrella', word: 'umbrella', translationJa: 'かさ', category: 'clothing' },
  { id: 'belt', word: 'belt', translationJa: 'ベルト', category: 'clothing' },
  { id: 'tie', word: 'tie', translationJa: 'ネクタイ', category: 'clothing' },
  { id: 'glasses', word: 'glasses', translationJa: 'めがね', category: 'clothing' },
  { id: 'backpack', word: 'backpack', translationJa: 'リュックサック', category: 'clothing' },
  { id: 'mittens', word: 'mittens', translationJa: 'ミトン', category: 'clothing' },
  { id: 'raincoat', word: 'raincoat', translationJa: 'レインコート', category: 'clothing' },
  { id: 'sandals', word: 'sandals', translationJa: 'サンダル', category: 'clothing' },
  { id: 'sunglasses', word: 'sunglasses', translationJa: 'サングラス', category: 'clothing' },
  { id: 'swimsuit', word: 'swimsuit', translationJa: 'みずぎ', category: 'clothing' },
  { id: 'apron', word: 'apron', translationJa: 'エプロン', category: 'clothing' },
  { id: 'helmet', word: 'helmet', translationJa: 'ヘルメット', category: 'clothing' },
  { id: 'socks', word: 'socks', translationJa: 'くつした', category: 'clothing' },
  { id: 'shorts', word: 'shorts', translationJa: 'はんずぼん', category: 'clothing' },
  { id: 'coat', word: 'coat', translationJa: 'コート', category: 'clothing' },
  { id: 'cap', word: 'cap', translationJa: 'キャップ', category: 'clothing' },
  { id: 'mask', word: 'mask', translationJa: 'マスク', category: 'clothing' },
  { id: 'ring', word: 'ring', translationJa: 'ゆびわ', category: 'clothing' },
  { id: 'necklace', word: 'necklace', translationJa: 'ネックレス', category: 'clothing' },
  { id: 'watch', word: 'watch', translationJa: 'うでどけい', category: 'clothing' },
  // household
  { id: 'bed', word: 'bed', translationJa: 'ベッド', category: 'household' },
  { id: 'chair', word: 'chair', translationJa: 'いす', category: 'household' },
  { id: 'table', word: 'table', translationJa: 'テーブル', category: 'household' },
  { id: 'sofa', word: 'sofa', translationJa: 'ソファ', category: 'household' },
  { id: 'door', word: 'door', translationJa: 'ドア', category: 'household' },
  { id: 'window', word: 'window', translationJa: 'まど', category: 'household' },
  { id: 'lamp', word: 'lamp', translationJa: 'ランプ', category: 'household' },
  { id: 'mirror', word: 'mirror', translationJa: 'かがみ', category: 'household' },
  { id: 'key', word: 'key', translationJa: 'かぎ', category: 'household' },
  { id: 'refrigerator', word: 'refrigerator', translationJa: 'れいぞうこ', category: 'household' },
  { id: 'oven', word: 'oven', translationJa: 'オーブン', category: 'household' },
  { id: 'sink', word: 'sink', translationJa: 'シンク', category: 'household' },
  { id: 'bathtub', word: 'bathtub', translationJa: 'バスタブ', category: 'household' },
  { id: 'toilet', word: 'toilet', translationJa: 'トイレ', category: 'household' },
  { id: 'toothbrush', word: 'toothbrush', translationJa: 'はぶらし', category: 'household' },
  { id: 'soap', word: 'soap', translationJa: 'せっけん', category: 'household' },
  { id: 'towel', word: 'towel', translationJa: 'タオル', category: 'household' },
  { id: 'pillow', word: 'pillow', translationJa: 'まくら', category: 'household' },
  { id: 'blanket', word: 'blanket', translationJa: 'もうふ', category: 'household' },
  { id: 'television', word: 'television', translationJa: 'テレビ', category: 'household' },
  { id: 'telephone', word: 'telephone', translationJa: 'でんわ', category: 'household' },
  { id: 'computer', word: 'computer', translationJa: 'コンピューター', category: 'household' },
  { id: 'book', word: 'book', translationJa: 'ほん', category: 'household' },
  { id: 'spoon', word: 'spoon', translationJa: 'スプーン', category: 'household' },
  { id: 'fork', word: 'fork', translationJa: 'フォーク', category: 'household' },
  { id: 'knife', word: 'knife', translationJa: 'ナイフ', category: 'household' },
  { id: 'plate', word: 'plate', translationJa: 'さら', category: 'household' },
  { id: 'cup', word: 'cup', translationJa: 'コップ', category: 'household' },
  { id: 'bowl', word: 'bowl', translationJa: 'ボウル', category: 'household' },
  { id: 'broom', word: 'broom', translationJa: 'ほうき', category: 'household' },
  { id: 'bucket', word: 'bucket', translationJa: 'バケツ', category: 'household' },
  { id: 'vacuum', word: 'vacuum', translationJa: 'そうじき', category: 'household' },
  { id: 'iron', word: 'iron', translationJa: 'アイロン', category: 'household' },
  { id: 'washingmachine', word: 'washing machine', translationJa: 'せんたくき', category: 'household' },
  { id: 'curtain', word: 'curtain', translationJa: 'カーテン', category: 'household' },
  { id: 'carpet', word: 'carpet', translationJa: 'じゅうたん', category: 'household' },
  { id: 'shelf', word: 'shelf', translationJa: 'たな', category: 'household' },
  { id: 'drawer', word: 'drawer', translationJa: 'ひきだし', category: 'household' },
  { id: 'candle', word: 'candle', translationJa: 'ろうそく', category: 'household' },
  { id: 'vase', word: 'vase', translationJa: 'かびん', category: 'household' },
  { id: 'basket', word: 'basket', translationJa: 'かご', category: 'household' },
  { id: 'teapot', word: 'teapot', translationJa: 'ティーポット', category: 'household' },
  { id: 'kettle', word: 'kettle', translationJa: 'やかん', category: 'household' },
  { id: 'pot', word: 'pot', translationJa: 'なべ', category: 'household' },
  { id: 'pan', word: 'pan', translationJa: 'フライパン', category: 'household' },
  { id: 'fan', word: 'fan', translationJa: 'せんぷうき', category: 'household' },
  { id: 'heater', word: 'heater', translationJa: 'ヒーター', category: 'household' },
  { id: 'ladder', word: 'ladder', translationJa: 'はしご', category: 'household' },
  { id: 'hammer', word: 'hammer', translationJa: 'トンカチ', category: 'household' },
  { id: 'screwdriver', word: 'screwdriver', translationJa: 'ドライバー', category: 'household' },
  { id: 'nail', word: 'nail', translationJa: 'くぎ', category: 'household' },
  { id: 'rope', word: 'rope', translationJa: 'ロープ', category: 'household' },
  { id: 'box', word: 'box', translationJa: 'はこ', category: 'household' },
  // school
  { id: 'pencil', word: 'pencil', translationJa: 'えんぴつ', category: 'school' },
  { id: 'eraser', word: 'eraser', translationJa: 'けしごむ', category: 'school' },
  { id: 'ruler', word: 'ruler', translationJa: 'じょうぎ', category: 'school' },
  { id: 'crayon', word: 'crayon', translationJa: 'クレヨン', category: 'school' },
  { id: 'glue', word: 'glue', translationJa: 'のり', category: 'school' },
  { id: 'notebook', word: 'notebook', translationJa: 'ノート', category: 'school' },
  { id: 'desk', word: 'desk', translationJa: 'つくえ', category: 'school' },
  { id: 'chalk', word: 'chalk', translationJa: 'チョーク', category: 'school' },
  { id: 'globe', word: 'globe', translationJa: 'ちきゅうぎ', category: 'school' },
  { id: 'calculator', word: 'calculator', translationJa: 'けいさんき', category: 'school' },
  { id: 'paintbrush', word: 'paintbrush', translationJa: 'ふで', category: 'school' },
  { id: 'blackboard', word: 'blackboard', translationJa: 'こくばん', category: 'school' },
  { id: 'bell', word: 'bell', translationJa: 'ベル', category: 'school' },
  { id: 'textbook', word: 'textbook', translationJa: 'きょうかしょ', category: 'school' },
  { id: 'marker', word: 'marker', translationJa: 'マーカー', category: 'school' },
  { id: 'stapler', word: 'stapler', translationJa: 'ホチキス', category: 'school' },
  { id: 'tape', word: 'tape', translationJa: 'テープ', category: 'school' },
  { id: 'clipboard', word: 'clipboard', translationJa: 'クリップボード', category: 'school' },
  { id: 'folder', word: 'folder', translationJa: 'フォルダー', category: 'school' },
  { id: 'scissors', word: 'scissors', translationJa: 'はさみ', category: 'school' },
  // weather
  { id: 'rain', word: 'rain', translationJa: 'あめ', category: 'weather' },
  { id: 'snow', word: 'snow', translationJa: 'ゆき', category: 'weather' },
  { id: 'wind', word: 'wind', translationJa: 'かぜ', category: 'weather' },
  { id: 'storm', word: 'storm', translationJa: 'あらし', category: 'weather' },
  { id: 'lightning', word: 'lightning', translationJa: 'いなずま', category: 'weather' },
  { id: 'thunder', word: 'thunder', translationJa: 'かみなり', category: 'weather' },
  { id: 'fog', word: 'fog', translationJa: 'きり', category: 'weather' },
  { id: 'ice', word: 'ice', translationJa: 'こおり', category: 'weather' },
  { id: 'hail', word: 'hail', translationJa: 'ひょう', category: 'weather' },
  { id: 'sunshine', word: 'sunshine', translationJa: 'ひざし', category: 'weather' },
  { id: 'breeze', word: 'breeze', translationJa: 'そよかぜ', category: 'weather' },
  { id: 'drizzle', word: 'drizzle', translationJa: 'こさめ', category: 'weather' },
  { id: 'frost', word: 'frost', translationJa: 'しも', category: 'weather' },
  { id: 'humidity', word: 'humidity', translationJa: 'しつど', category: 'weather' },
  // body parts
  { id: 'head', word: 'head', translationJa: 'あたま', category: 'bodyPart' },
  { id: 'hair', word: 'hair', translationJa: 'かみのけ', category: 'bodyPart' },
  { id: 'eye', word: 'eye', translationJa: 'め', category: 'bodyPart' },
  { id: 'ear', word: 'ear', translationJa: 'みみ', category: 'bodyPart' },
  { id: 'nose', word: 'nose', translationJa: 'はな', category: 'bodyPart' },
  { id: 'mouth', word: 'mouth', translationJa: 'くち', category: 'bodyPart' },
  { id: 'teeth', word: 'teeth', translationJa: 'は', category: 'bodyPart' },
  { id: 'hand', word: 'hand', translationJa: 'て', category: 'bodyPart' },
  { id: 'finger', word: 'finger', translationJa: 'ゆび', category: 'bodyPart' },
  { id: 'arm', word: 'arm', translationJa: 'うで', category: 'bodyPart' },
  { id: 'leg', word: 'leg', translationJa: 'あし', category: 'bodyPart' },
  { id: 'toe', word: 'toe', translationJa: 'あしゆび', category: 'bodyPart' },
  { id: 'knee', word: 'knee', translationJa: 'ひざ', category: 'bodyPart' },
  { id: 'shoulder', word: 'shoulder', translationJa: 'かた', category: 'bodyPart' },
  { id: 'tongue', word: 'tongue', translationJa: 'した', category: 'bodyPart' },
  { id: 'neck', word: 'neck', translationJa: 'くび', category: 'bodyPart' },
  { id: 'elbow', word: 'elbow', translationJa: 'ひじ', category: 'bodyPart' },
  { id: 'chin', word: 'chin', translationJa: 'あご', category: 'bodyPart' },
  // toys
  { id: 'ball', word: 'ball', translationJa: 'ボール', category: 'toy' },
  { id: 'doll', word: 'doll', translationJa: 'にんぎょう', category: 'toy' },
  { id: 'kite', word: 'kite', translationJa: 'たこ', category: 'toy' },
  { id: 'blocks', word: 'blocks', translationJa: 'つみき', category: 'toy' },
  { id: 'puzzle', word: 'puzzle', translationJa: 'パズル', category: 'toy' },
  { id: 'robot', word: 'robot', translationJa: 'ロボット', category: 'toy' },
  { id: 'teddybear', word: 'teddy bear', translationJa: 'くまのぬいぐるみ', category: 'toy' },
  { id: 'yoyo', word: 'yo-yo', translationJa: 'ヨーヨー', category: 'toy' },
  { id: 'top', word: 'top', translationJa: 'こま', category: 'toy' },
  { id: 'marbles', word: 'marbles', translationJa: 'びーだま', category: 'toy' },
  { id: 'trampoline', word: 'trampoline', translationJa: 'トランポリン', category: 'toy' },
  { id: 'skateboard', word: 'skateboard', translationJa: 'スケートボード', category: 'toy' },
  { id: 'jumprope', word: 'jump rope', translationJa: 'なわとび', category: 'toy' },
  { id: 'dice', word: 'dice', translationJa: 'さいころ', category: 'toy' },
  { id: 'slide', word: 'slide', translationJa: 'すべりだい', category: 'toy' },
  { id: 'swing', word: 'swing', translationJa: 'ぶらんこ', category: 'toy' },
  // sports
  { id: 'soccer', word: 'soccer', translationJa: 'サッカー', category: 'sport' },
  { id: 'baseball', word: 'baseball', translationJa: 'やきゅう', category: 'sport' },
  { id: 'basketball', word: 'basketball', translationJa: 'バスケットボール', category: 'sport' },
  { id: 'tennis', word: 'tennis', translationJa: 'テニス', category: 'sport' },
  { id: 'swimming', word: 'swimming', translationJa: 'すいえい', category: 'sport' },
  { id: 'running', word: 'running', translationJa: 'ランニング', category: 'sport' },
  { id: 'skiing', word: 'skiing', translationJa: 'スキー', category: 'sport' },
  { id: 'skating', word: 'skating', translationJa: 'スケート', category: 'sport' },
  { id: 'surfing', word: 'surfing', translationJa: 'サーフィン', category: 'sport' },
  { id: 'golf', word: 'golf', translationJa: 'ゴルフ', category: 'sport' },
  { id: 'volleyball', word: 'volleyball', translationJa: 'バレーボール', category: 'sport' },
  { id: 'badminton', word: 'badminton', translationJa: 'バドミントン', category: 'sport' },
  { id: 'boxing', word: 'boxing', translationJa: 'ボクシング', category: 'sport' },
  { id: 'judo', word: 'judo', translationJa: 'じゅうどう', category: 'sport' },
  // instruments
  { id: 'piano', word: 'piano', translationJa: 'ピアノ', category: 'instrument' },
  { id: 'guitar', word: 'guitar', translationJa: 'ギター', category: 'instrument' },
  { id: 'violin', word: 'violin', translationJa: 'バイオリン', category: 'instrument' },
  { id: 'trumpet', word: 'trumpet', translationJa: 'トランペット', category: 'instrument' },
  { id: 'flute', word: 'flute', translationJa: 'フルート', category: 'instrument' },
  { id: 'xylophone', word: 'xylophone', translationJa: 'シロホン', category: 'instrument' },
  { id: 'harp', word: 'harp', translationJa: 'ハープ', category: 'instrument' },
  { id: 'recorder', word: 'recorder', translationJa: 'リコーダー', category: 'instrument' },
  { id: 'drum', word: 'drum', translationJa: 'たいこ', category: 'instrument' },
  { id: 'tambourine', word: 'tambourine', translationJa: 'タンバリン', category: 'instrument' },
  // shapes
  { id: 'circle', word: 'circle', translationJa: 'まる', category: 'shape' },
  { id: 'square', word: 'square', translationJa: 'しかく', category: 'shape' },
  { id: 'triangle', word: 'triangle', translationJa: 'さんかく', category: 'shape' },
  { id: 'rectangle', word: 'rectangle', translationJa: 'ちょうほうけい', category: 'shape' },
  { id: 'oval', word: 'oval', translationJa: 'だえん', category: 'shape' },
  { id: 'diamond', word: 'diamond', translationJa: 'ひしがた', category: 'shape' },
  { id: 'pentagon', word: 'pentagon', translationJa: 'ごかくけい', category: 'shape' },
  { id: 'hexagon', word: 'hexagon', translationJa: 'ろっかくけい', category: 'shape' },
  { id: 'cube', word: 'cube', translationJa: 'りっぽうたい', category: 'shape' },
  { id: 'sphere', word: 'sphere', translationJa: 'たま', category: 'shape' },
  // places
  { id: 'park', word: 'park', translationJa: 'こうえん', category: 'place' },
  { id: 'zoo', word: 'zoo', translationJa: 'どうぶつえん', category: 'place' },
  { id: 'beach', word: 'beach', translationJa: 'かいがん', category: 'place' },
  { id: 'farm', word: 'farm', translationJa: 'のうじょう', category: 'place' },
  { id: 'station', word: 'station', translationJa: 'えき', category: 'place' },
  { id: 'library', word: 'library', translationJa: 'としょかん', category: 'place' },
  { id: 'school', word: 'school', translationJa: 'がっこう', category: 'place' },
  { id: 'hospital', word: 'hospital', translationJa: 'びょういん', category: 'place' },
  { id: 'playground', word: 'playground', translationJa: 'あそびば', category: 'place' },
  { id: 'garden', word: 'garden', translationJa: 'にわ', category: 'place' },
  { id: 'bridge', word: 'bridge', translationJa: 'はし', category: 'place' },
  { id: 'lighthouse', word: 'lighthouse', translationJa: 'とうだい', category: 'place' },
]

export function getWordById(id: string): WordEntry {
  const entry = wordBank.find((w) => w.id === id)
  if (!entry) {
    throw new Error(`Unknown word id: ${id}`)
  }
  return entry
}

/** Held back from every quiz category that draws on wordBank (englishWords,
 * spotDifference, logic) until BOTH its pronunciation and its flashcard image have
 * been explicitly confirmed correct — either one failing is enough to exclude a word,
 * so a bad image never shows up (as a quiz target, a distractor, or a spot-the-
 * difference/odd-one-out icon) paired with correct audio, or vice versa. Assets
 * (image, audio file) stay on disk under public/ — only question selection skips
 * these ids. Remove an id here once *both* its audio and image are confirmed.
 *
 * Audio-unresolved (pronunciation still wrong after five rounds of fix attempts —
 * see the word-pronunciation project memory):
 * pasta, taco, turquoise, umbrella, socks, ostrich, eye
 *
 * Image-unconfirmed (regenerated via the standard, non-Lightning RealVisXL checkpoint
 * after the Lightning-checkpoint version was reviewed as low quality, but not yet
 * re-confirmed by a human reviewer — see the word-image-review project memory):
 * breeze, caterpillar, chalk, chin, comet, crane, crayon, cucumber, desert, diamond,
 * drizzle, elbow, farm, firefly, garden, glacier, glue, hail, hair, head, humidity,
 * jumprope, ketchup, knee, lighthouse, mango, mayonnaise, mole, mountain, nail,
 * omelette, oval, pentagon, platypus, plum, porcupine, recorder, rectangle, root,
 * sand, shelf, shoulder, skating, soda, square, squid, stingray, tambourine, tapir,
 * textbook, thunder, top, valley, volcano, wind, xylophone, yoyo, zoo
 *
 * (comet: regenerated to look visually distinct from meteor per QA — the fix reads as
 * a bright starburst/nebula rather than a recognizable comet, rejected on review.)
 */
export const EXCLUDED_WORD_IDS = new Set([
  // audio-unresolved
  'pasta', 'taco', 'turquoise', 'umbrella', 'socks', 'ostrich', 'eye',
  // image-unconfirmed
  'breeze', 'caterpillar', 'chalk', 'chin', 'comet', 'crane', 'crayon', 'cucumber',
  'desert', 'diamond', 'drizzle', 'elbow', 'farm', 'firefly', 'garden', 'glacier',
  'glue', 'hail', 'hair', 'head', 'humidity', 'jumprope', 'ketchup', 'knee',
  'lighthouse', 'mango', 'mayonnaise', 'mole', 'mountain', 'nail', 'omelette', 'oval',
  'pentagon', 'platypus', 'plum', 'porcupine', 'recorder', 'rectangle', 'root', 'sand',
  'shelf', 'shoulder', 'skating', 'soda', 'square', 'squid', 'stingray', 'tambourine',
  'tapir', 'textbook', 'thunder', 'top', 'valley', 'volcano', 'wind', 'xylophone',
  'yoyo', 'zoo',
])

/** wordBank filtered to only words eligible for quiz use — see EXCLUDED_WORD_IDS. */
export function eligibleWordBank(): WordEntry[] {
  return wordBank.filter((w) => !EXCLUDED_WORD_IDS.has(w.id))
}
