export interface WordEntry {
  id: string
  word: string
  translationJa: string
  category: 'animal' | 'food' | 'nature' | 'color' | 'vehicle'
}

export const wordBank: WordEntry[] = [
  { id: 'dog', word: 'dog', translationJa: 'いぬ', category: 'animal' },
  { id: 'cat', word: 'cat', translationJa: 'ねこ', category: 'animal' },
  { id: 'bird', word: 'bird', translationJa: 'とり', category: 'animal' },
  { id: 'fish', word: 'fish', translationJa: 'さかな', category: 'animal' },
  { id: 'rabbit', word: 'rabbit', translationJa: 'うさぎ', category: 'animal' },
  { id: 'bear', word: 'bear', translationJa: 'くま', category: 'animal' },
  { id: 'elephant', word: 'elephant', translationJa: 'ぞう', category: 'animal' },
  { id: 'lion', word: 'lion', translationJa: 'らいおん', category: 'animal' },
  { id: 'horse', word: 'horse', translationJa: 'うま', category: 'animal' },
  { id: 'cow', word: 'cow', translationJa: 'うし', category: 'animal' },
  { id: 'pig', word: 'pig', translationJa: 'ぶた', category: 'animal' },
  { id: 'sheep', word: 'sheep', translationJa: 'ひつじ', category: 'animal' },
  { id: 'duck', word: 'duck', translationJa: 'あひる', category: 'animal' },
  { id: 'chicken', word: 'chicken', translationJa: 'にわとり', category: 'animal' },
  { id: 'frog', word: 'frog', translationJa: 'かえる', category: 'animal' },
  { id: 'turtle', word: 'turtle', translationJa: 'かめ', category: 'animal' },
  { id: 'penguin', word: 'penguin', translationJa: 'ぺんぎん', category: 'animal' },
  { id: 'monkey', word: 'monkey', translationJa: 'さる', category: 'animal' },
  { id: 'tiger', word: 'tiger', translationJa: 'とら', category: 'animal' },
  { id: 'zebra', word: 'zebra', translationJa: 'しまうま', category: 'animal' },
  { id: 'giraffe', word: 'giraffe', translationJa: 'きりん', category: 'animal' },
  { id: 'panda', word: 'panda', translationJa: 'ぱんだ', category: 'animal' },
  { id: 'koala', word: 'koala', translationJa: 'こあら', category: 'animal' },
  { id: 'fox', word: 'fox', translationJa: 'きつね', category: 'animal' },
  { id: 'owl', word: 'owl', translationJa: 'ふくろう', category: 'animal' },
  { id: 'butterfly', word: 'butterfly', translationJa: 'ちょう', category: 'animal' },
  { id: 'bee', word: 'bee', translationJa: 'はち', category: 'animal' },
  { id: 'ladybug', word: 'ladybug', translationJa: 'てんとうむし', category: 'animal' },
  { id: 'snail', word: 'snail', translationJa: 'かたつむり', category: 'animal' },
  { id: 'squirrel', word: 'squirrel', translationJa: 'りす', category: 'animal' },
  { id: 'hedgehog', word: 'hedgehog', translationJa: 'はりねずみ', category: 'animal' },
  { id: 'deer', word: 'deer', translationJa: 'しか', category: 'animal' },
  { id: 'kangaroo', word: 'kangaroo', translationJa: 'かんがるー', category: 'animal' },
  { id: 'apple', word: 'apple', translationJa: 'りんご', category: 'food' },
  { id: 'banana', word: 'banana', translationJa: 'バナナ', category: 'food' },
  { id: 'grape', word: 'grape', translationJa: 'ぶどう', category: 'food' },
  { id: 'strawberry', word: 'strawberry', translationJa: 'いちご', category: 'food' },
  { id: 'orange', word: 'orange', translationJa: 'オレンジ', category: 'food' },
  { id: 'watermelon', word: 'watermelon', translationJa: 'すいか', category: 'food' },
  { id: 'bread', word: 'bread', translationJa: 'パン', category: 'food' },
  { id: 'egg', word: 'egg', translationJa: 'たまご', category: 'food' },
  { id: 'cake', word: 'cake', translationJa: 'ケーキ', category: 'food' },
  { id: 'pizza', word: 'pizza', translationJa: 'ぴざ', category: 'food' },
  { id: 'hamburger', word: 'hamburger', translationJa: 'はんばーがー', category: 'food' },
  { id: 'hotdog', word: 'hotdog', translationJa: 'ほっとどっぐ', category: 'food' },
  { id: 'rice', word: 'rice', translationJa: 'ごはん', category: 'food' },
  { id: 'noodles', word: 'noodles', translationJa: 'めん', category: 'food' },
  { id: 'sushi', word: 'sushi', translationJa: 'すし', category: 'food' },
  { id: 'cookie', word: 'cookie', translationJa: 'くっきー', category: 'food' },
  { id: 'donut', word: 'donut', translationJa: 'どーなつ', category: 'food' },
  { id: 'icecream', word: 'ice cream', translationJa: 'あいすくりーむ', category: 'food' },
  { id: 'milk', word: 'milk', translationJa: 'ぎゅうにゅう', category: 'food' },
  { id: 'cheese', word: 'cheese', translationJa: 'ちーず', category: 'food' },
  { id: 'carrot', word: 'carrot', translationJa: 'にんじん', category: 'food' },
  { id: 'tomato', word: 'tomato', translationJa: 'とまと', category: 'food' },
  { id: 'potato', word: 'potato', translationJa: 'じゃがいも', category: 'food' },
  { id: 'corn', word: 'corn', translationJa: 'とうもろこし', category: 'food' },
  { id: 'broccoli', word: 'broccoli', translationJa: 'ぶろっこりー', category: 'food' },
  { id: 'mushroom', word: 'mushroom', translationJa: 'きのこ', category: 'food' },
  { id: 'pineapple', word: 'pineapple', translationJa: 'ぱいなっぷる', category: 'food' },
  { id: 'peach', word: 'peach', translationJa: 'もも', category: 'food' },
  { id: 'lemon', word: 'lemon', translationJa: 'れもん', category: 'food' },
  { id: 'sun', word: 'sun', translationJa: 'たいよう', category: 'nature' },
  { id: 'star', word: 'star', translationJa: 'ほし', category: 'nature' },
  { id: 'heart', word: 'heart', translationJa: 'はーと', category: 'nature' },
  { id: 'moon', word: 'moon', translationJa: 'つき', category: 'nature' },
  { id: 'flower', word: 'flower', translationJa: 'はな', category: 'nature' },
  { id: 'balloon', word: 'balloon', translationJa: 'ふうせん', category: 'nature' },
  { id: 'cloud', word: 'cloud', translationJa: 'くも', category: 'nature' },
  { id: 'mountain', word: 'mountain', translationJa: 'やま', category: 'nature' },
  { id: 'tree', word: 'tree', translationJa: 'き', category: 'nature' },
  { id: 'leaf', word: 'leaf', translationJa: 'は', category: 'nature' },
  { id: 'rock', word: 'rock', translationJa: 'いし', category: 'nature' },
  { id: 'grass', word: 'grass', translationJa: 'くさ', category: 'nature' },
  { id: 'seashell', word: 'seashell', translationJa: 'かいがら', category: 'nature' },
  { id: 'pinecone', word: 'pinecone', translationJa: 'まつぼっくり', category: 'nature' },
  { id: 'acorn', word: 'acorn', translationJa: 'どんぐり', category: 'nature' },
  { id: 'cactus', word: 'cactus', translationJa: 'さぼてん', category: 'nature' },
  { id: 'rainbow', word: 'rainbow', translationJa: 'にじ', category: 'nature' },
  { id: 'coconut', word: 'coconut', translationJa: 'やしのみ', category: 'nature' },
  { id: 'red', word: 'red', translationJa: 'あか', category: 'color' },
  { id: 'blue', word: 'blue', translationJa: 'あお', category: 'color' },
  { id: 'yellow', word: 'yellow', translationJa: 'きいろ', category: 'color' },
  { id: 'green', word: 'green', translationJa: 'みどり', category: 'color' },
  { id: 'purple', word: 'purple', translationJa: 'むらさき', category: 'color' },
  { id: 'pink', word: 'pink', translationJa: 'ピンク', category: 'color' },
  { id: 'brown', word: 'brown', translationJa: 'ちゃいろ', category: 'color' },
  { id: 'black', word: 'black', translationJa: 'くろ', category: 'color' },
  { id: 'car', word: 'car', translationJa: 'くるま', category: 'vehicle' },
  { id: 'bus', word: 'bus', translationJa: 'バス', category: 'vehicle' },
  { id: 'train', word: 'train', translationJa: 'でんしゃ', category: 'vehicle' },
  { id: 'airplane', word: 'airplane', translationJa: 'ひこうき', category: 'vehicle' },
  { id: 'bicycle', word: 'bicycle', translationJa: 'じてんしゃ', category: 'vehicle' },
  { id: 'boat', word: 'boat', translationJa: 'ふね', category: 'vehicle' },
  { id: 'ship', word: 'ship', translationJa: 'せんぱく', category: 'vehicle' },
  { id: 'motorcycle', word: 'motorcycle', translationJa: 'おーとばい', category: 'vehicle' },
  { id: 'helicopter', word: 'helicopter', translationJa: 'へりこぷたー', category: 'vehicle' },
  { id: 'truck', word: 'truck', translationJa: 'とらっく', category: 'vehicle' },
  { id: 'tractor', word: 'tractor', translationJa: 'とらくたー', category: 'vehicle' },
  { id: 'scooter', word: 'scooter', translationJa: 'すくーたー', category: 'vehicle' },
]

export function getWordById(id: string): WordEntry {
  const entry = wordBank.find((w) => w.id === id)
  if (!entry) {
    throw new Error(`Unknown word id: ${id}`)
  }
  return entry
}
