#!/usr/bin/env python3
"""Builds src/domain/spotScenes.ts from scripts/spot-themes.json plus the generated images
in public/images/spot/<theme>/ (see generate-spot-scenes-local.py). Only themes whose
background exists, and only sprites whose PNG exists, are included — so a partial or
in-progress generation still yields a working (smaller) set.

Per sprite it measures:
  - aspect: width / height of the cropped sticker, so the tap box matches the picture;
  - flippable: taken from the theme's human-reviewed "flippable" list — a mirror-flip is only
    a fair "difference" when a child can actually see it (a fish facing the other way), not
    for a ball or a front-facing crab. A silhouette-mirror score is printed next to each
    sprite as a hint for that review; it isn't reliable enough to decide on its own (the
    crab scored high on slight claw differences nobody would notice).

Usage: python3 scripts/build-spot-scenes.py
"""
import json
import os

import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THEMES = json.load(open(os.path.join(ROOT, "scripts", "spot-themes.json")))
OUT = os.path.join(ROOT, "src", "domain", "spotScenes.ts")
# Background differences (one recoloured area of bg.jpg each) — see build-spot-bg-variants.py.
BG_DIFFS_PATH = os.path.join(ROOT, "scripts", "spot-bg-diffs.json")
BG_DIFFS = json.load(open(BG_DIFFS_PATH)) if os.path.exists(BG_DIFFS_PATH) else {}
# …plus the AI-repainted ones (generate-spot-bg-inpaint.py), listed per theme the same way.
BG_INPAINT_PATH = os.path.join(ROOT, "scripts", "spot-bg-inpaint-diffs.json")
for _theme, _diffs in (json.load(open(BG_INPAINT_PATH)) if os.path.exists(BG_INPAINT_PATH) else {}).items():
    BG_DIFFS[_theme] = BG_DIFFS.get(_theme, []) + _diffs


def mirror_difference(path):
    """Silhouette mismatch with its own mirror image: 1 - IoU(shape, mirrored shape). Only
    the outline counts — tiny shading or centering differences don't, since a child judges
    "is it facing the other way?" by shape (fish ~0.3+, crab/ball ~0.05)."""
    im = Image.open(path).convert("RGBA")
    im.thumbnail((128, 128))
    shape = np.asarray(im)[..., 3] > 128
    mirrored = shape[:, ::-1]
    union = np.logical_or(shape, mirrored).sum()
    return float(1 - np.logical_and(shape, mirrored).sum() / union) if union else 0.0


themes_out = []
for theme_id, spec in THEMES.items():
    folder = os.path.join(ROOT, "public", "images", "spot", theme_id)
    if not os.path.exists(os.path.join(folder, "bg.jpg")):
        continue
    sprites = []
    for sid in spec["sprites"]:
        path = os.path.join(folder, f"{sid}.png")
        if not os.path.exists(path):
            continue
        w, h = Image.open(path).size
        score = mirror_difference(path)
        sprites.append({
            "id": sid,
            "zones": spec["spriteZones"][sid],
            "aspect": round(w / h, 3),
            "flippable": sid in set(spec.get("flippable", [])),
            # Recoloured / part-changed versions of this sticker, when they exist (see
            # build-spot-color-variants.py and generate-spot-part-variants.py).
            "colorVariant": os.path.exists(os.path.join(folder, f"{sid}__color.png")),
            "partVariant": os.path.exists(os.path.join(folder, f"{sid}__part.png")),
            "_mirror": round(score, 3),
        })
    # A zone is one rectangle or a list of them (e.g. sand on both sides of a lagoon).
    zones = {name: (r if isinstance(r[0], list) else [r]) for name, r in spec["zones"].items()}
    if len(sprites) >= 6:
        bg_diffs = [d for d in BG_DIFFS.get(theme_id, []) if os.path.exists(os.path.join(folder, f"bg__{d['id']}.jpg"))]
        themes_out.append({"id": theme_id, "zones": zones, "sprites": sprites, "bgDiffs": bg_diffs})

lines = [
    "/** GENERATED by scripts/build-spot-scenes.py from scripts/spot-themes.json and the images in",
    " * public/images/spot/ — do not hand-edit. Each zone is one or more [x0, x1, y0, y1] rectangles in",
    " * % of the panel (where an object's center may go); aspect is the sticker's width / height;",
    " * flippable says whether a mirror-flip is a visible difference for that picture; colorVariant /",
    " * partVariant say whether <id>__color.png (same picture, different colour) / <id>__part.png (one",
    " * part changed — a shorter tail, a longer beak, different eyes) exist for it. */",
    "export interface SpotSprite {",
    "  id: string",
    "  zones: string[]",
    "  aspect: number",
    "  flippable: boolean",
    "  colorVariant: boolean",
    "  partVariant: boolean",
    "}",
    "",
    "/** One changed area of the background (bg__<id>.jpg — recoloured, or repainted by AI); rect is [x0, x1, y0, y1] in % of the panel. */",
    "export interface SpotBgDiff {",
    "  id: string",
    "  rect: [number, number, number, number]",
    "}",
    "",
    "export interface SpotTheme {",
    "  id: string",
    "  zones: Record<string, [number, number, number, number][]>",
    "  sprites: SpotSprite[]",
    "  bgDiffs: SpotBgDiff[]",
    "}",
    "",
    "export const SPOT_THEMES: SpotTheme[] = " + json.dumps(
        [{**t, "sprites": [{k: v for k, v in s.items() if not k.startswith("_")} for s in t["sprites"]]} for t in themes_out],
        ensure_ascii=False, indent=2,
    ),
    "",
]
open(OUT, "w").write("\n".join(lines))
for t in themes_out:
    print(t["id"], " ".join(f"{s['id']}:{s['_mirror']}{'(flip)' if s['flippable'] else ''}" for s in t["sprites"]))
print(f"wrote {OUT} ({len(themes_out)} themes)")
